### ISSUE TITLE
SystemError: error return without exception set

### ISSUE THREAD

**Issue by kingel** [gorakhargosh/watchdog#100]
Sometimes I this error and watchdog doesn't work at all, any ideas on what is happening?

File "/Users/franklin/.buildout/eggs/watchdog-0.6.0-py2.7-macosx-10.4-x86_64.egg/watchdog/observers/fsevents.py", line 189, in run
    self.pathnames)
SystemError: error return without exception set

**Comment by BoboTiG** [comment]
I am closing that issue as it is quite old. Open a new one if necessary.
