### ISSUE TITLE
Inconsistent Triggering of on_created Event

### ISSUE THREAD

**Issue by RagnarLothbrok-Odin** [gorakhargosh/watchdog#1022]
### Use Case
I am utilizing the `watchdog` library to monitor a directory for screenshots created with the default Mac screenshot tool. The objective is to detect these screenshots upon creation and subsequently upload the files. The challenge arises because the `on_created` event is inconsistently triggered, sometimes detecting the main file and other times only capturing the hidden file generated by macOS during the screenshot process.

#### Observation
Upon investigating, it appears that when a screenshot is taken on a Mac, the system initially saves the file as a hidden file. After processing, the hidden file is updated to the final image file. The issue manifests in that the `on_created` event is occasionally triggered for the 'main' file (when it transitions from being a hidden file) and sometimes only for the hidden file. Importantly, the hidden file is not classified as a proper file, hence the need for a return statement in such scenarios.

#### Confirmation
To validate this theory, I included the following code snippet:

```python
def on_modified(self, event):
    if not os.path.isfile(event.src_path):
        return
    print(f"Modified file: {os.path.basename(event.src_path)}")
    
def on_created(self, event):
    print(f"Created file: {os.path.basename(event.src_path)}")
```

### Example Scenarios
1. **Scenario A:**
    - Created file: `.Screenshot 2023-12-07 at 11.35.41.png`
    - Modified file: `Screenshot 2023-12-07 at 11.35.41.png`
    
    Here, the initial `on_created` trigger is for the temporary file, followed by a `on_modified` trigger for the complete file after modification.

2. **Scenario B:**
    - Created file: `.Screenshot 2023-12-07 at 11.35.47.png`
    - Modified file: `Screenshot 2023-12-07 at 11.35.47.png`
    - Created file: `Screenshot 2023-12-07 at 11.35.47.png`
    
    In this case, the `on_created` event is triggered twice – once for the temporary file and once for the final file creation.

### Reproduction Steps
To reproduce the issue, create a screenshot using macOS and observe the event triggers.

### Additional Information
- The issue seems to be specific to macOS and its handling of temporary files during the creation process.

## Possible Solutions
The challenge lies in separating the upload function (see below for the GitHub URL for my repository) into its own function while monitoring for `on_modified`. A potential solution involves devising a mechanism to prevent processing the same file twice, possibly by tracking file names using a queue or similar data structure.

## Additional Context
The complete code is available here: https://github.com/Valhalla-Development/ZiplineAutoUpload

**Comment by BoboTiG** [comment]
Thank you for the detailed report 🥂 

Would it be possible for you to run that command from within the test folder before running your manual tests?

```console
$ watchmedo log --recursive .
```

I bet it will be very helpful for both of us, I am looking for other types of events that could be leveraged 🤞🏻

**Comment by RagnarLothbrok-Odin** [comment]
I am going to close this issue, it took me a few days to figure out the logic in my head to be honest, but I got it in the end!
https://github.com/Valhalla-Development/ZiplineAutoUpload/commit/abc5924487ba12070ebeb84d44befdf43d4e108d
