### ISSUE TITLE
Installation fails with 4.0.0

### ISSUE THREAD

**Issue by wizrds** [gorakhargosh/watchdog#1030]
I'm getting the following error with poetry and pip since about 6 minutes ago on our CI and locally as well:

```
  • Updating watchdog (3.0.0 -> 4.0.0)
  RuntimeError
  Unable to find installation candidates for watchdog (4.0.0)
  at .venv/lib/python3.11/site-packages/poetry/installation/chooser.py:73 in choose_for
       69│ 
       70│             links.append(link)
       71│ 
       72│         if not links:
    →  73│             raise RuntimeError(f"Unable to find installation candidates for {package}")
       74│ 
       75│         # Get the best link
       76│         chosen = max(links, key=lambda link: self._sort_key(package, link))
       77│ 
Cannot install watchdog.
```

I believe the dependency comes from `mkdocs`. I noticed the PyPI release files only contains macos releases, could this be why?

**Comment by command-tab** [comment]
Installation of `watchdog` 4.0.0 succeeds for me on Apple Silicon macOS, but fails on x86_64 Linux. I ran into this when attempting to build and deploy one of my web apps which depends on `dramatiq`, which leads to `watchdog` further down the dependency chain.

**Comment by BoboTiG** [comment]
Hm maybe is it a PyPI cache issue? All files seem present here: https://pypi.org/project/watchdog/4.0.0/#files 🤔

**Comment by wizrds** [comment]
> Hm maybe is it a PyPI cache issue? All files seem present here: https://pypi.org/project/watchdog/4.0.0/#files 🤔

I'm seeing nothing but macos files there 
![image](https://github.com/gorakhargosh/watchdog/assets/91095492/90afd169-6fa5-4c17-9b35-3ebf247acf3a)

**Comment by altendky** [comment]
https://github.com/gorakhargosh/watchdog/actions/runs/7806785223 the artifact only has the macOS wheels same as I see on PyPI at your link.  https://github.com/gorakhargosh/watchdog/actions/runs/7806785223/job/21294176071 also shows it skipping the publish step.  I guess you uploaded manually?

**Comment by altendky** [comment]
https://github.com/gorakhargosh/watchdog/commit/1ce88d5813b1a334962ebc7742916584d80fe999 you need to do more than this to adjust for v4.  I'll take a look after dinner.

**Comment by leandrodamascena** [comment]
I'm getting the same error here:

```sh
❯ python
Python 3.9.6 (default, Jun 24 2022, 23:59:22) 
[GCC 12.1.1 20220507 (Red Hat 12.1.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

```sh
❯ pip install watchdog==4.0.0
ERROR: Could not find a version that satisfies the requirement watchdog==4.0.0 (from versions: 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.6.0, 0.7.0, 0.7.1, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.9.0, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.10.4, 0.10.5, 1.0.0, 1.0.1, 1.0.2, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.1.7, 2.1.8, 2.1.9, 2.2.0, 2.2.1, 2.3.0, 2.3.1, 3.0.0)
ERROR: No matching distribution found for watchdog==4.0.0
WARNING: You are using pip version 21.1.3; however, version 24.0 is available.
You should consider upgrading via the '/tmp/auu/.venv/bin/python3.9 -m pip install --upgrade pip' command.
```

**Comment by BoboTiG** [comment]
Oh!

No, the action should take care of all OS. I'll look into it right now.

**Comment by BoboTiG** [comment]
> [1ce88d5](https://github.com/gorakhargosh/watchdog/commit/1ce88d5813b1a334962ebc7742916584d80fe999) you need to do more than this to adjust for v4. I'll take a look after dinner.

OK I just had a look at https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md. I'll push a fix + missing wheels.

**Comment by leandrodamascena** [comment]
> > [1ce88d5](https://github.com/gorakhargosh/watchdog/commit/1ce88d5813b1a334962ebc7742916584d80fe999) you need to do more than this to adjust for v4. I'll take a look after dinner.
> 
> OK I just had a look at [actions/upload-artifact@`main`/docs/MIGRATION.md](https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md?rgh-link-date=2024-02-06T23%3A33%3A39Z). I'll push a fix + missing wheels.

You are using the same name for all artifacts, so, you need to add the new parameter `overwrite: true` in the upload-artifact@v4.

**Comment by wizrds** [comment]
> > [1ce88d5](https://github.com/gorakhargosh/watchdog/commit/1ce88d5813b1a334962ebc7742916584d80fe999) you need to do more than this to adjust for v4. I'll take a look after dinner.
> 
> OK I just had a look at https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md. I'll push a fix + missing wheels.

I appreciate the quick response :+1:

**Comment by BoboTiG** [comment]
Build is ongoing: https://github.com/BoboTiG/watchdog/actions/runs/7807583000

**Comment by altendky** [comment]
Don't think we want to overwrite...  In fact, that's probably what is happening now thus no error like I got a couple weeks ago when I dealt with the upgrade.

**Comment by altendky** [comment]
https://github.com/BoboTiG/watchdog/commit/d134073f44701fb28126e73bd952c666d3adc68e looks, at a glance, like what I did.  There's also the question of the publish step not running.

**Comment by leandrodamascena** [comment]
> Don't think we want to overwrite... In fact, that's probably what is happening now thus no error like I got a couple weeks ago when I dealt with the upgrade.

You have the option to add overwrite or change the name of the artifact, both work. But agree with you, changing the name is better :)

**Comment by BoboTiG** [comment]
Yup, I reverted the "overwrite" stuff. I just didn't understand what it does.

**Comment by altendky** [comment]
Overwrite looks like it deletes the existing artifact so you end up with just the last set of files.

**Comment by altendky** [comment]
Ah, it's supposed to run publish when triggered manually via workflow dispatch.

**Comment by BoboTiG** [comment]
@altendky the publish step not running is expected. I run the publish workflow from my fork since I do nit have access to that repository secrets.

**Comment by leandrodamascena** [comment]
> Overwrite looks like it deletes the existing artifact so you end up with just the last set of files.

OK, OK, OK, you're 100% right @altendky! I read the workflow again and it only publishes the files in the last step, so it deletes the files from the previous step and will only publish the last file.
Thanks

**Comment by BoboTiG** [comment]
Meh, I did not fix the workflow properly. Copy-pasta error 👏🏻 
Will try again right now.

**Comment by leandrodamascena** [comment]
Working!
![image](https://github.com/gorakhargosh/watchdog/assets/4295173/ea3ed78d-7c55-4cac-86f2-0affb3e4ac91)

**Comment by BoboTiG** [comment]
This seems good finally! 🍾 

Thank you all for feedbacks and hints 💪🏻

**Comment by altendky** [comment]
When they first did this and broke the world, it at least _broke_ the world and hard failed instead of silently changing behavior to overwriting the whole thing.  Oh well.

**Comment by will-holley** [comment]
If you use Poetry and are still encountering this issue because your `watchdog` definition in your lock file doesn't include the full `4.0.0` wheel set, try clearing your cache with `poetry cache clear pypi:watchdog:4.0.0`.
