### ISSUE TITLE
Unable to find installation candidates on v4.0.0

### ISSUE THREAD

**Issue by adrielp** [gorakhargosh/watchdog#1031]
Yesterday, this package was updated and auto pulled in through some workflows. Consistently, we were getting the following error: 

```
  • Installing watchdog (4.0.0)

  RuntimeError

  Unable to find installation candidates for watchdog (4.0.0)

  at ~/.local/share/pypoetry/venv/lib/python3.11/site-packages/poetry/installation/chooser.py:73 in choose_for
       69│ 
       70│             links.append(link)
       71│ 
       72│         if not links:
    →  73│             raise RuntimeError(f"Unable to find installation candidates for {package}")
       74│ 
       75│         # Get the best link
       76│         chosen = max(links, key=lambda link: self._sort_key(package, link))
       77│ 

Cannot install watchdog.
```

Reverted to version 3.0.0 to temporarily solve the issue.

**Comment by BoboTiG** [comment]
It was reported and fixed quickly yesterday (see #1030).
It's surprising you still have an issue 🤔

**Comment by BoboTiG** [comment]
And you still encounter an error right now? I see all files available for GNU/Linux in https://pypi.org/project/watchdog/4.0.0/#files.

**Comment by adrielp** [comment]
I think you can close this. It might've been some weird runner caching issue. Checked another repo with the same package, no issue. Then had the dependency manager open a PR with that bump to v4.0.0 in the troublesome repo and the workflows passed this time. There's no explicit caching on our end in the workflow, so must've been something on the backend. 

Appreciate the quick response!

**Comment by adrielp** [comment]
Ok, I reopened because I just saw it happen in a completely unrelated repo. For context, we have multiple mkdocs sites and this is one of the packages that gets used as part of this. 

My suspicion is that it could be a load balancing/mirroring issue. but yea it's definitely still an issue. Though might not be with the package itself.

**Comment by BoboTiG** [comment]
I think we can close the issue, there are cache issues somewhere, but it's outside our capabilities.
