### ISSUE TITLE
Implement separately events of contents updating and attributes changing

### ISSUE THREAD

**Issue by atercattus** [gorakhargosh/watchdog#110]
For example in Inotify.queue_events():
          elif event.is_attrib:
            klass = ACTION_EVENT_MAP[(event.is_directory,
                                      EVENT_TYPE_MODIFIED)]
            self.queue_event(klass(event.src_path))

In tasks of files synchronization it is necessary to check the file's size and hash when attributes were simply changed.

Can add new ACTION_EVENT_MAP items like as "(True, EVENT_TYPE_ATTRS) : AttrModifiedEvent" or FileSystemEvent.is_attr_changed property?

I apologize for my bad English.

**Comment by BoboTiG** [comment]
Let's move the discussion to #260.
