### ISSUE TITLE
Pypy support for FSEvents

### ISSUE THREAD

**Issue by edevil** [gorakhargosh/watchdog#118]
it would be nice if we could use this package with Pypy. Right now at least the FSEvents C extension will not compile under Pypy. I think the problem lies in the GIL handling code present in the C code.

**Comment by mscansian** [comment]
Is there any news on this issue? It has been almost 4 years and watchdog is still not running in PyPy.
For what I understand the problem is not watchdog itself, there are some dependencies that are incompatible. Am I right?
