### ISSUE TITLE
FSEventsObserver doesn't work on Mac OS X 10.8

### ISSUE THREAD

**Issue by jezdez** [gorakhargosh/watchdog#126]
I'm not certain what causes the problem to be honest, I'm running 10.8.1 with the latest XCode (i686-apple-darwin11-llvm-gcc-4.2 (GCC) 4.2.1)

Running `watchmedo log` with `--debug-force-fsevents` won't show anything either.

I'm running:

```
watchmedo log -R -p py acme
```

**Comment by BoboTiG** [comment]
Closing as 10.8 is very old and not supported.
