### ISSUE TITLE
watchmedo shell-command: drop events during execution of command

### ISSUE THREAD

**Issue by jenisys** [gorakhargosh/watchdog#136]
(original title): watchmedo shell-command --wait seems to fire more often than necessary 

Version: watchdog 0.6.0

When I execute the watchmedo script with "--wait --command=..." seems to be triggered to often. The command seems to be executed for each detected event according to the generated command-output. This seems to unnecessary and inefficient. Normally, I would expect the following behavior

```
# -- PSEUDO-CODE:
loop forever:
    Wait until event occurs.
    Remove all pending events (from the scheduler queue).
    Execute the command (once for all removed/pending events)
```

**REASON:**
When the command is executed it should rebuild whatever and be responsible for all accumulated events.

The efficient behaviour could also be enabled by a new, additional command-line option.

**NOTE:**
If you do not use the "--wait" option you can still use the nice debug/diag feature:

```
watchmedo shell-command ... --command='echo "${watch_src_path}"'
```

to detect which filesystem events occurred.

**Comment by cefn** [comment]
Great little utility, thanks. The watchmedo feature I was hoping for (and I think others too from rummaging around in feature requests), may be different than --drop, which is to say, if there are a batch of changes happening, I don't want the shell-command to be run until _after_ the changes have all happened, and only to happen once, as they are all the result of the same cascade of events. 

In other words I would like the system to wait for X milliseconds after each event to see if there's other events to be batched together with it, and then finally trigger the command after the first X milliseconds monitored without changes. You might call it --idletrigger

--drop seems to trigger the shell command immediately when the first change happens, and then ignore subsequent changes, which is quite a different feature set, highly likely to trigger race conditions, and a bit surprising that it's what people want, assuming they're using it for the kind of cascade commands I'm working with - recursively monitoring whole directories where a recompile has extensive knock-on changes which influence a lot of files, and where those knock-on effects may take quite a few milliseconds to fully propagate. It's not just the first change which should be noticed, or the ones which have raced to be completed in time, and the next pipeline should only be triggered _after_ all the changes are complete 

By all means tell me if my testing is wrong and I've misunderstood --drop. Also happy to refile a new issue if others subscribed to this this one really do want --drop and don't want --idletrigger Also I may have missed the full help or manual file as I can't seem to find a complete list of the commands available in my copy of watchmedo, so it may be hidden in another command line flag which I haven't examined, yet. 

    watchmedo --help

...doesn't list the --drop flag, for example, although it seems to be honored and...

    man watchmedo

...says the utility is undocumented in man.

**Comment by hayd** [comment]
@cefn That seems reasonable to me, what would make sense IMO/for me:

1. wait a bit of time to start (X milliseconds)
2. run command(s)
3. if event happens while running, cancel previous command (^C), go back to 1.

(doing `watchmedo shell-command --help` gets the specific help, with drop and wait.)

**Comment by hayd** [comment]
@cefn I have a PR which does this, adding a --terminate argument. #319

**Comment by Asday** [comment]
@nuket I know it's been a long time, but is there any room to resubmit that PR?  What @cefn described is exactly what I want.

1.  `git checkout branch`
2.  Git changes files one at a time
3.  On the first file, `watchmedo shell-command` starts executing

I don't want that.  I want watchmedo to start executing on the _last_ file change.  Obviously that's not possible to detect, but a smoothing of a couple milliseconds would perfectly solve the issue.  This is a well-known concept in programming too, for instance, [lodash](https://css-tricks.com/debouncing-throttling-explained-examples/#article-header-id-0) has a function called `debounce`.

**Comment by felix-last** [comment]
Agree with @Asday and others here. Anyone finding this, a new issue on the topic has been opened: https://github.com/gorakhargosh/watchdog/issues/315
