### ISSUE TITLE
Optimize FSEvents and Kqueue snapshotting

### ISSUE THREAD

**Issue by gorakhargosh** [gorakhargosh/watchdog#18]
Currently, for any event both these emitters snapshot the entire directory tree
to compare for changes. If we know which directory the change occurred in
we can modify the DirectorySnapshot class to update itself with only that
part of the tree and return a diff of events within that subtree. This should
save quite a bit of I/O.

**Comment by SamSchott** [comment]
This can probably be closed now?

**Comment by BoboTiG** [comment]
You are right @SamSchott, it was fixed with 3b9904c74ad0eae628471d22d584b4582344e761, in v0.10.4.

**Comment by SamSchott** [comment]
The oldest open issue is finally closed 🎉

**Comment by BoboTiG** [comment]
Yup, the project is moving forward thanks to our great contributors :)
