### ISSUE TITLE
Is there a way to pause the observer?

### ISSUE THREAD

**Issue by Ayrx** [gorakhargosh/watchdog#181]
I'm working with watchdog to implement a syncing functionality for a directory. 

The problem I am facing is with Watchdog "uploading" everything I "downloaded" to the watched directory which causes some looping issues.

I need a way to "pause" the observer thread while I do whatever that needs to be done before "unpausing" the thread. Is there a way to accomplish this?

Cheers!

**Comment by ShahriyarR** [comment]
Well, in my use case, pausing observer is needed as i want to calculate progress of files(byte size) every 10 seconds for eg. If i will implement it with sleep(10) inside EventHandler it will calculate progress even there are no changes on directory, leading to endless calculation.
For me this code portion worked:
```python
class PausingObserver(Observer):
    def dispatch_events(self, *args, **kwargs):
        if not getattr(self, '_is_paused', False):
            super(PausingObserver, self).dispatch_events(*args, **kwargs)

    def pause(self):
        self._is_paused = True

    def resume(self):
        time.sleep(10)  # allow interim events to be queued
        self.event_queue.queue.clear()
        self._is_paused = False
```


And from now we can use pause and resume for eg, with on_created() event:

```python

class ProgressEstimate(FileSystemEventHandler):
def on_created(self, event):
        observer.pause()
        observer.resume()
        dest_folder_size = self.get_size_of_folder(event.src_path)
        print("Backup folder size {}".format(dest_folder_size))
```

The main section:

```python
if __name__ == "__main__":
    
    logging.basicConfig(level=logging.INFO,
                        format='%(asctime)s - %(message)s',
                        datefmt='%Y-%m-%d %H:%M:%S')

    dest_path = sys.argv[1]
    observer = PausingObserver()
    event_handler = ProgressEstimate()
    observer.schedule(event_handler, dest_path, recursive=True)
    observer.start()
    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        observer.stop()
    observer.join()
```
