### ISSUE TITLE
Event after closing file (close_write)

### ISSUE THREAD

**Issue by ghost** [gorakhargosh/watchdog#184]
Is there a way to get the an event after a file is closed similar to pyinotify's IN_CLOSE_WRITE event?  I'm trying to monitor very large files and I really only need the write close event rather than the "Modified file" spam.

**Comment by BoboTiG** [comment]
Finally implemented with 2fab7c2a06df0785a322186b191d0cd7c95f566a (will be part of the 1.0.3 version).
