### ISSUE TITLE
install bug while using pip and easy install on Mac OSX 10.9

### ISSUE THREAD

**Issue by timtan** [gorakhargosh/watchdog#224]
Below is the error message ! 

$ sudo easy_install watchdog

Searching for watchdog
Reading http://pypi.python.org/simple/watchdog/
Best match: watchdog 0.7.1
Downloading https://pypi.python.org/packages/source/w/watchdog/watchdog-0.7.1.tar.gz#md5=ffec8b4afd1058e76f6c664ade8a0de7
Processing watchdog-0.7.1.tar.gz
Running watchdog-0.7.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-UAZdio/watchdog-0.7.1/egg-dist-tmp-5qroIO
no previously-included directories found matching 'docs/source/_themes/.git*'
clang: error: unknown argument: '-mno-fused-madd' [-Wunused-command-line-argument-hard-error-in-future]
clang: note: this will be a hard error (cannot be downgraded to a warning) in the future
error: Setup script exited with error: command 'cc' failed with exit status 1

**Comment by diegoiglesias** [comment]
@chestozo worked for OSX 10.9, thanks.
>sudo -E pip install watchdog
