### ISSUE TITLE
Allow importing / selecting observer

### ISSUE THREAD

**Issue by adiroiban** [gorakhargosh/watchdog#253]
Right now, `observers/__init__.py` always tries to import and select a predefined observer.

I have 2 problems with this:
- on RHEL 4, libc version is older and inotity_c.py fails with `Unsupported libc version found: libc.so.6` ... I still want to support RHEL 4 even with degraded directory pooling
- on Windows 2003 and above you need special privileges to call ReadDirectoryChangesW (I guess SE_BACKUP_NAME and SE_RESTORE_NAME privileges) ... for accounts without this privilege, I prefer to have a custom warning and check for exact condition, rather than the default generic message "Failed to import read_directory_changes. Fall back to polling." 

I am working on a multi-user application, so on windows for one user I can use ReadDirectory while for other only PollingObserver so I want to import both.

Not sure how to fix this in a backward compatible way.

---

For now, I fixed this for myself by forking the project and removing all content for init module. I now manually and dynamically chose what observer implementation to use for each specific usage.

**Comment by oberstet** [comment]
we (crossbar.io) are affected by this, in as watchdog is a dep, and it breaks things on buildroot/ulibc.

rgd testing, docker and travis can be integrated, eg https://github.com/crossbario/autobahn-java/blob/master/.travis.yml

sadly, RHEL 4 is so old, that there doesn't seem to be images: https://hub.docker.com/_/centos/

mmh .. dunno. I don't have such old crap (rhel4) around either, and I understand projects don't have time for this ..

**Comment by BoboTiG** [comment]
For uClibc, a patch has been merged with 268a46d.
As for other ideas here, some work has been done a while ago to fallback on polling on error.

Please open a specific ticket issue for any issue :)
