### ISSUE TITLE
Is buildbot still used

### ISSUE THREAD

**Issue by adiroiban** [gorakhargosh/watchdog#262]
I saw that the repo has some buildout configs... but the bootstrap.py is obsolete.

is buildout still used... if not, maybe it should be removed to clean the repo...

I also saw a tox.ini file ... in case it is used, maybe it should be documented in some contributing doc

Thanks!

**Comment by BoboTiG** [comment]
+1 to clean up buildbot files.

**Comment by rrzaripov** [comment]
@BoboTiG I want to make this job, but I need some explanations about project files.
After reviewing repository, my opinion is:
* ``bootstrap.sh`` - downloading and installing buidout, file will be removed
* ``buildout.cfg`` - configuration for buildout, file will be removed
* ``Makefile`` - i think Makefile it is more actual for package maintainers in linux community.  But if this file stay in project, it is need to be reworked:
  - test - switch to pytest
  - upload-doc - now docs on readthedocs, not PyPi and no need to update it
  - develop - remove if we cut off buildout
  - release - not need, now using CI
  - auto - not need, now using CI
  - push - not actual

* ``package.mk`` - merge to Makefile or remove.
* ``debian`` - package settings for watchdog version 0.5.4, and Debian 7 Wheezy (out of support). I don't actually know, how works maintainers in Debian, but I think all additionally needed files like ``package.mk``, ``Makefile`` and ``debian`` directory must be live in maintainers repository as patches to original project. If it is so, possible we can remove ``package.mk``, ``Makefile`` and ``debian`` from repository? By the way, in Debain repositories watchdog  represented by version [0.8.3](https://packages.debian.org/stretch/python-watchdog).
* ``tools`` - only watchmedo.bat I think need to be save, all other files will be removed.

P.S. documentation must be updated after this changes.
P.P.S. this is only my opinion, and must be discussion, before changes. Please any notes, advises and opinions welcome!

**Comment by BoboTiG** [comment]
OK @rrzaripov; it would be great to make this cleanup :)
I `tools` you can save `dump_fsevents_constants.py` too, it may be useful for someone.
