### ISSUE TITLE
schedule() after unschedule_all() fails on OSX

### ISSUE THREAD

**Issue by parente** [gorakhargosh/watchdog#27]
<pre>
>>> from watchdog.observers import Observer
>>> from watchdog.events import LoggingEventHandler
>>> ob = Observer()
>>> ob.start()
>>> event_handler = LoggingEventHandler()
>>> ob.schedule(event_handler, '.')
<ObservedWatch: path=/Users/parente/projects/handlerbag, is_recursive=False>
>>> ob.unschedule_all()
>>> event_handler = LoggingEventHandler()
>>> ob.schedule(event_handler, '.')
<ObservedWatch: path=/Users/parente/projects/handlerbag, is_recursive=False>
>>> Exception in thread Thread-3:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/threading.py", line 522, in __bootstrap_inner
    self.run()
  File "/Users/parente/envs/rst/src/watchdog/src/watchdog/observers/fsevents.py", line 145, in run
    pathnames)
SystemError: error return without exception set
</pre>

**Comment by BoboTiG** [comment]
Fixed since 0.7.0.
