### ISSUE TITLE
Unexpected behavior when using pattern like "foo*"

### ISSUE THREAD

**Issue by mouadino** [gorakhargosh/watchdog#273]
Hi,

This kind of pattern is useful when you want to match rotated files (like logs) for example, but this doesn't work, b/c the pathtools apparently choose to match per path and not with filename like python fnmatch stdlib !

So something like this doesn't work:

```
watchmedo log --pattern="foo*" /var/log/bar
```

instead you have to do:

```
watchmedo log --pattern="/var/log/bar/foo*" /var/log/bar
```

HTH,

**Comment by BoboTiG** [comment]
Moving the discussion to #798.
