### ISSUE TITLE
Need to be able to enforce the usage of PollingObserver

### ISSUE THREAD

**Issue by peterlauri** [gorakhargosh/watchdog#290]
In my environment I have a vagrant box (virtualbox Ubuntu 12.04) and need to monitor changes that happens both on host and guest. The virtualbox shared folder implementation does not propagate the file change events from the host to the guest, so the default InotifyObserver will not work.

I have created a pull request #289 that implements this.

**Comment by mafrosis** [comment]
Related to #316

**Comment by BoboTiG** [comment]
Is it fixed with #336?

**Comment by BoboTiG** [comment]
Merged 7a726d1.
