### ISSUE TITLE
Use a non-root logger

### ISSUE THREAD

**Issue by genericmoniker** [gorakhargosh/watchdog#293]
It would be nice if watchdog didn't write to the root logger (that is, calling logging.debug), but rather created its own logger (logging.getLogger). That would give application writers more control over the output.

I notice this with inotify_buffer.py especially. While I generally would like the root logger to log at DEBUG in my application, doing so means that my log file gets flooded with "InotifyBuffer" messages when there's a bunch of IO in a watched location. If watchdog had its own logger, I could set the level for that independently.

**Comment by tamland** [comment]
Already fixed. #274. Sorry for the inconvenience
