### ISSUE TITLE
SystemExit is catched from event handlers

### ISSUE THREAD

**Issue by untitaker** [gorakhargosh/watchdog#294]
I expect the following code to exit when something happens. Instead, I have to use something based on threading events:

    import sys
    import time
    import logging
    from watchdog.observers import Observer
    from watchdog.events import FileSystemEventHandler

    class _CustomHandler(FileSystemEventHandler):
        def on_modified(self, event):
            print("BYE")
            sys.exit(3)

        on_created = on_modified

    if __name__ == "__main__":
        observer = Observer()
        observer.start()
        observer.schedule(_CustomHandler(), sys.argv[1], recursive=True)
        try:
            while True:
                time.sleep(1)
        except KeyboardInterrupt:
            observer.stop()
        observer.join()

**Comment by tamland** [comment]
I think you may have misread that commit. It catches RuntimeError which is raised if the thread had not been started, not SystemExit. Revering d5eb1e31c535a4076ad51f18594e70c1940437ec does not fix your example.

I am not sure why you expect this to exit the process nor how that changed between v0.8.1 and v0.8.2. sys.exit only works from the main thread.

**Comment by untitaker** [comment]
In hindsight this behavior makes total sense, yeah. I didn't know about the restriction that SystemExit is only effective from the main thread. I also didn't test whether this derived testcase would fail under different versions.

In other words, sorry for the noise.
