### ISSUE TITLE
make yaml a extra dependency

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [gorakhargosh/watchdog#297]
i'd love to use the core package, but i don't want the yaml dependency and i don't use the script

**Comment by ralsina** [comment]
Same here. We are thinking about moving to watchdog from pure inotify in [Nikola](http://getnikola.com) and [Doit](http://pydoit.org) but the YAML dependency is hard to take.

**Comment by Kwpolska** [comment]
I’d love to send a pull request, but I can’t get buildout to work.  Here’s my patch for this feature instead:

```diff
diff --git a/setup.py b/setup.py
index ba7283c..8c27538 100644
--- a/setup.py
+++ b/setup.py
@@ -81,7 +81,7 @@ tests_require=['pytest', 'pytest-cov', 'pytest-timeout >=0.3']
 if sys.version_info < (2, 7, 0):
     tests_require.append('unittest2')
 
-install_requires = ['PyYAML >=3.10', 'argh >=0.24.1', 'pathtools >=0.1.1']
+install_requires = ['argh >=0.24.1', 'pathtools >=0.1.1']
 if sys.version_info < (2, 7, 0):
     # argparse is merged into Python 2.7 in the Python 2x series
     # and Python 3.2 in the Python 3x series.
@@ -92,6 +92,8 @@ if sys.version_info < (2, 7, 0):
         # which works.
         install_requires.append('select_backport >=0.2')
 
+cmd_requires = ['PyYAML >=3.10']
+
 with open('README.rst') as f:
     readme = f.read()
 
@@ -142,6 +144,7 @@ setup(name="watchdog",
       packages=find_packages(SRC_DIR),
       include_package_data=True,
       install_requires=install_requires,
+      extras_require={'cmd': cmd_requires},
       tests_require=tests_require,
       cmdclass={
           'build_ext': build_ext,
```


core-only usage:

    $ pip install watchdog

cmd usage:

    $ pip install "watchdog[cmd]"


**Maintainers:** please review and apply if possible, we’d all appreciate it :smiley:

**Comment by RonnyPfannschmidt** [comment]
The extra also needs to be added to script entrypoints

**Comment by fluffy-critter** [comment]
Nearly four years later, and a dependency on watchdog is causing all of my projects to get GitHub security audit alerts for a dependency on a library that's not even used by consumers of the library. Any chance this could get looked at again?

Thanks!

**Comment by BoboTiG** [comment]
Of course, will open a PR for discussion.
