### ISSUE TITLE
Separate dispatch handler function calling from filtering logic

### ISSUE THREAD

**Issue by biesnecker** [gorakhargosh/watchdog#307]
Right now the existing FileSystemEventHandlers' `dispatch` functions contain both the logic for filtering events and the logic for calling the right handler functions. This makes it difficult to patch in support for things like asyncio or gevent, which could reuse the filtering and dispatch logic but need to call the handler functions in a different way. 

This could be solved by splitting the creation of `_method_map` out of the `dispatch` function, so that just that could be overridden in `FileSystemEventHandler` subclasses.

**Comment by BoboTiG** [comment]
PR are welcome if you find it still interesting :)

**Comment by BoboTiG** [comment]
Won't do for now, see the linked issue for details.
