### ISSUE TITLE
Large file raises multiple modified events

### ISSUE THREAD

**Issue by debnet** [gorakhargosh/watchdog#309]
Microsoft Windows - Python 3.4.3 - Watchdog 0.8.3

With large files, watchdog raises multiple modified events on copy so it's impossible to know when a file write is complete in order to perform actions after.

```
[09/04/2015 15:28:59]    INFO: Created C:\Temp\fr_visual_studio_premium_2012_x86_dvd_920761.iso
[09/04/2015 15:28:59]    INFO: Modified C:\Temp\fr_visual_studio_premium_2012_x86_dvd_920761.iso
[09/04/2015 15:29:09]    INFO: Modified C:\Temp\fr_visual_studio_premium_2012_x86_dvd_920761.iso
[09/04/2015 15:29:09]    INFO: Modified C:\Temp\fr_visual_studio_premium_2012_x86_dvd_920761.iso
[09/04/2015 15:29:09]    INFO: Modified C:\Temp\fr_visual_studio_premium_2012_x86_dvd_920761.iso
```

**Comment by frmdstryr** [comment]
Just use a timeout that calls a function when it expires and reset the timeout on each modified event.

**Comment by haekelmeister** [comment]
I have the same behaviour here, that's really annoying! Why there is no way to provided a method like `on_files_copied`?

**Comment by helkr** [comment]
@frmdstryr can you provide an example of how to use the timeout for that? I have the same problem and found similar cases online of duplicate events being returned, but not a single explicit solution. Thank you

**Comment by frmdstryr** [comment]
I don't have the code anymore (previous company). You need to use a timer or integrate it with an event loop of some sort that has a way to call a function after some timeout. Then something like this should work

```python

def call_later(ms,callback, *args, **kwargs):
   #: Timer/event loop specific
   #: called after the given ms "timeout" expires 
   callback(*args, **kwargs)

class Handler(FileSystemEventHandler):
    pending = 0 #: Must be accessed in a thread safe way if using a timer/threads

    def on_modified(self,event):
        self.pending += 1
        #: Call after
        call_later(200,self.on_modifications_complete, event)

    def on_modifications_complete(self, event):
       self.pending -=1
       if self.pending==0:
           #: Modification is done do your handling here

```

The `on_modifications_complete` is still called for every event just with a 200ms delay but when the modifications stop (ie pending==0) you know it hasn't been updated in the past 200ms (or whatever delay) and can be considered "done". 

If you need to handle multiple files just make "pending" counters for each file (ex a dictionary with keys of the file path and value of a counter) and check each one.

**Comment by helkr** [comment]
@frmdstryr I have never used event loops before, so I am not sure how to do this integration. For example, I found the code below for scheduling a callback. How can it be integrated with yours? I am only watching a specific file.

My apologies if the question is inadequate for the post. I'm a grad student in civil engineering trying to make a newbie code work.

 ```
import asyncio

    async def main(loop):
        loop.call_later(1, on_modifications_complete, event)

        await asyncio.sleep(0.4)

    event_loop = asyncio.get_event_loop()
    try:
        print('entering event loop')
        event_loop.run_until_complete(main(event_loop))
    finally:
        print('closing event loop')
        event_loop.close()
```

**Comment by helkr** [comment]
Nevermind. I solved the issue by only using 'on_created' instead of 'on_modified'. I created a function to rename the watched file everytime there's a change. This way every new change is understood as a new created file event, and I can keep track of all the different versions.

**Comment by BoboTiG** [comment]
This is the desired behavior. Therefore I am closing the issue.

**Comment by ruslankrivoshein** [comment]
@BoboTiG, explain, please, why it is desired
