### ISSUE TITLE
Adding the write close event

### ISSUE THREAD

**Issue by derekschrock** [gorakhargosh/watchdog#313]
Would it be possible to have a write close event?
This would be valuable to monitor file when copy finishes.

**Comment by tuxinaut** [comment]
:+1:

**Comment by aig-** [comment]
+1

**Comment by tamland** [comment]
Not in a portable way. It would be inotify only (maybe windows too). See #217

**Comment by ph-hs** [comment]
`openssl rand 1000000000 -out biiig.file` makes a file big enough that watchdog notifies a couple of times during the file being written. 

We have to write our own "quiet time" logic to ensure the the file has finished being written to?

**Comment by rrzaripov** [comment]
@BoboTiG same issue as in #567

**Comment by mortoray** [comment]
Unfortunately the lack of this feature makes this library very difficult to use. There are numerous software applications that write in a serialized fashion to the file, generating many modified events. It's not safe to respond to any of those events and access the file.

Is there some other way to detect this state, and/or lock it?

**Comment by BoboTiG** [comment]
Even if the write-close event is not portable, let's implement it where we can.

We are open to suggestions and PRs :)

**Comment by BoboTiG** [comment]
Finally implemented the inotify part with 2fab7c2a06df0785a322186b191d0cd7c95f566a (will be part of the 1.0.3 version).
Let's open specific issues for other OSes, if required.
