### ISSUE TITLE
watchdog.utils.platform.is_bsd() is always false

### ISSUE THREAD

**Issue by magv** [gorakhargosh/watchdog#320]
Hi. Currently watchdog uses [this code](/gorakhargosh/watchdog/blob/v0.8.3/src/watchdog/utils/platform.py#L29-39) to detect current platform:

``` python
def get_platform_name():
    if sys.platform.startswith("win"):
        return PLATFORM_WINDOWS
    elif sys.platform.startswith('darwin'):
        return PLATFORM_DARWIN
    elif sys.platform.startswith('linux'):
        return PLATFORM_LINUX
    elif sys.platform.startswith('bsd'):
        return PLATFORM_BSD
    else:
        return PLATFORM_UNKNOWN
```

This code doesn't really work. On FreeBSD 10 `sys.platform` is set to `'freebsd10'`, and `'freebsd10'.starswith('bsd')` is false, so this code always returns `PLATFORM_UNKNOWN`. As a consequence, the default observer on FreeBSD is the polling-based one, not the kqueue-based one.

Could you change the platform detection to something like the following instead?

``` python
def get_platform_name():
    if 'darwin' in sys.platform:
        return PLATFORM_DARWIN
    elif 'win' in sys.platform:
        return PLATFORM_WINDOWS
    elif 'linux' in sys.platform:
        return PLATFORM_LINUX
    elif 'bsd' in sys.platform:
        return PLATFORM_BSD
    else:
        return PLATFORM_UNKNOWN
```

**Comment by simplytunde** [comment]
Seems like the same issue has been pointed out in issue [#312](https://github.com/gorakhargosh/watchdog/issues/312).

**Comment by magv** [comment]
Yeah, it's the same issue (I did not notice it initially). There's been no response to that issue in two months though...

**Comment by magv** [comment]
Also note that `kqueue` observer is somewhat broken: it does not create a listener for the top level directory (`DirectorySnapshot` only lists the children and skips the parent), so if new files are added to it, the observer will not see them. This was not an issue before, because that observer was never used, but if platform detection is to be fixed, the observer should be fixed as well.
