### ISSUE TITLE
Delayed/No file change events on Windows 8.1

### ISSUE THREAD

**Issue by andrewpmartinez** [gorakhargosh/watchdog#327]
I'm seeing an issue where I am attempting to follow log files that another process is writing.

If I have the file open in Sublime 2 I can see the file changing as events are logged, but I do not see any events being fired from Watchdog. If I open the directory where the logs are and click on the log file being written to (not open, just select), Watchdog then generates events for file changes.

I attempted to fall back to polling (by using PollingObserver), but then I stopped receiving events when the file is selected.

If I wait long enough (10min+) Watchdog will fire a file change event, but seems oddly long.

Python 3.4.3
Windows 8.1

**Comment by Gloorf** [comment]
I have the same issue, did you managed to solve it (other than opening the directory and clicking on the log file) ?

**Comment by andrewpmartinez** [comment]
I was on Windows as stated in the original issue. The problem seems to be that however the program was writing to the logs, it was never signaling to windows that any writing had been done. Thus, the file system was never firing events and watchdog was never being triggered.

I solved my problem by polling the file and reading new lines if they existed.

**Comment by Gloorf** [comment]
I came to the same conclusion and ended doing the same thing. Thanks for the answer !
