### ISSUE TITLE
Various issues with {Regex,Pattern}MatchingEventHandler

### ISSUE THREAD

**Issue by anntzer** [gorakhargosh/watchdog#335]
- Currently, full paths are matched to the regexes using `re.match`, which only looks for matches at the beginning of the string.  It would probably make sense to use `re.search` instead, or to match the file name without the directory name.  (This makes it much easier to match actual patterns e.g. `r"^foo\d\d\d\.dat$"` which currently has to be written `r".*/foo\d\d\d\.dat$"` on a POSIX system and `r".*\\foo\d\d\d\.dat$"` on a Windows system.)
- If it is decided that RegexMatchingEventHandler should still match the full path (which is not silly), it would be useful to normalize the path separator to "/" to make cross-platform code easier to write.
- For both Regex and PatternMatchingEventHandler, it would make sense to default case-sensitivity to the platform default (i.e. yes on POSIX, no on Windows).

**Comment by ArmEagle** [comment]
Ah thank you for the pointer about the pattern having to include the path. I couldn't get something like `abc.*123` work.

**Comment by humitos** [comment]
I was bitten by this. It's not clear to me how to use the `--ignore-patterns` glob-style syntax. I ended at https://github.com/gorakhargosh/watchdog/blob/master/src/watchdog/utils/patterns.py#L30-L31 noticing that it uses `PurePosixPath.match` (https://docs.python.org/3.11/library/pathlib.html#pathlib.PurePath.match)

However, I wasn't able to make this example to work:

```
In [44]: path
Out[44]: PurePosixPath('.tox/py38/lib/python3.8/site-packages/pip/_vendor/urllib3/util/timeout.py')

In [45]: path.match('.tox/**/*.py')
Out[45]: False

In [46]: path.match('.tox/')
Out[46]: False
```

I'm not sure how I need to write my pattern to match "everything that starts with `.tox`" for example 🤷🏼

**Comment by BoboTiG** [comment]
Let's continue the discussion on #798.
