### ISSUE TITLE
the wheel is not platform independent 

### ISSUE THREAD

**Issue by jiminsong** [gorakhargosh/watchdog#341]
The wheel built from a linux machine doesn't work on a Mac OS X machine due to the failure to import _watchdog_fsevents. Thus, the platform tag in the wheel name built from a linux machine shouldn't be "any".
- I generated the wheel from a linux machine:

```
$ pip wheel watchdog
```
- I copied it to a Mac machine and installed it:

```
$ pip install watchdog-0.8.3-py2-none-any.whl
```
- I failed to import _watchdog_fsevents in python on a Mac OS X.

``` python
>>> import _watchdog_fsevents
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named _watchdog_fsevents
```

**Comment by paul-hammant** [comment]
Wheels don't require qualifiers for the platform?

I mean like Java jars do in MavenCentral where native code is included? Ref: http://central.maven.org/maven2/org/bytedeco/javacpp-presets/opencv/3.2.0-1.3/

**Comment by BoboTiG** [comment]
There is not wheel as of now because of the macOS dependencie. Follow #428 instead.
