### ISSUE TITLE
On OSX Observer starts at schedule, not at start

### ISSUE THREAD

**Issue by KenV99** [gorakhargosh/watchdog#343]
In testing on multiple platforms, on Linux and Windows, Observer can be instantiated and 'scheduled' but doesn't start until .start() is called.

On OSX, Observer starts sending events to EventHandler at the time of .schedule() and doesn't wait for .start().

**Comment by BoboTiG** [comment]
It is not more the case. The `schedule()` method just calls the parents one after unicode uniformization.
