### ISSUE TITLE
No module named observers on windows OS

### ISSUE THREAD

**Issue by xsank** [gorakhargosh/watchdog#352]
watchdog has been installed successfully.
`Successfully installed argh-0.26.1 pathtools-0.1.2 watchdog-0.8.3`
but the watchdog is not complete
`>>> dir(watchdog)
['CHECK_PORT_FILE', 'CHECK_PORT_PROCESS_COMMAND', 'CHECK_PORT_PROCESS_SOCKET_COM
MAND', 'MAX_DEADTIME', 'MAX_FULL_GC_COUNT', 'MAX_FULL_GC_PERCENT', 'MAX_KILL_TIM
EOUT', 'MAX_START_CHECK_COUNT', 'MAX_STOP_TIMEOUT', 'PROJECT_DIR', 'PROJECT_LOG_
FILE', 'PROJECT_START_SCRIPT', 'WatchDog', '__builtins__', '__doc__', '__file__'
, '__name__', '__package__', 'commands', 'glob', 'os', 'run_command', 'time']`

**Comment by MapZombie** [comment]
Also getting the same error...

**Comment by memmaker** [comment]
Same here.

**Comment by EngineerCoding** [comment]
Currently downgraded to v0.8.2 where the import does seem to work. I am not sure yet wether the watcher itself will work, will update this after testing.

```
python -m pip uninstall watchdog
python -m pip install watchdog==0.8.2
```

**Comment by BoboTiG** [comment]
Closing as it is well tested that `observers` are present on all platforms. Open a speicif issue if encountering the error again.

**Comment by ErYoung2** [comment]
Perhaps you named your python file as "watchdog" or "observers"...
Try to rename it and run again.
