### ISSUE TITLE
Not working on MacOs 10.10.5

### ISSUE THREAD

**Issue by cdancette** [gorakhargosh/watchdog#359]
I tried to watch a directory, and watchdog doesn't detect changes in the file when using the default observer (FSQueue). When i use kqueue, it works.

**Comment by fx86** [comment]
@cdancette - I'm unable to install Watchdog on OSX 10.10.5. Could you let me know how you did it please ?

**Comment by BoboTiG** [comment]
Closing as it lacks of information and it is quite old.
