### ISSUE TITLE
Build available without watchmedo?

### ISSUE THREAD

**Issue by kathychurch** [gorakhargosh/watchdog#364]
I was wondering if there is a version available without the watchmedo tool?  I would love to use watchdog, but the LGPL license on the argh library is an issue.

**Comment by devster31** [comment]
If there isn't I would still suggest splitting the library from the command-line tool, extra dependencies aren't always needed.

**Comment by gorakhargosh** [comment]
Good idea. We'll work towards this.

**Comment by mmerickel** [comment]
I also think it'd be great if watchmedo was split into a separate package. I'm looking at integrating watchdog into pyramid's pserve wsgi runner and adding a dependency on pyyaml is definitely a concern.

**Comment by y2kbugger** [comment]
I agree, a good first step would be to convert watchmedo deps to optional 'extras_requires'. Right now I have to add --no-deps to my tools readme.. to get around this.

**Comment by chrahunt** [comment]
From the README, `watchmedo` is now opt-in:

```
$ python -m pip install watchdog

# or to install the watchmedo utility:
$ python -m pip install watchdog[watchmedo]
```

So this can be closed?

**Comment by BoboTiG** [comment]
You are right, it was done with a37e1ae1503f6c8c2a88cffe76c74012af23c9f9 but not yet released.
