### ISSUE TITLE
How to monitor event when the file is closed?

### ISSUE THREAD

**Issue by igordavid** [gorakhargosh/watchdog#367]
Hello,

We have a problem with using Watchdog when we want to detect when the write has been finished and file is closed.

At the moment we can't do that as we are seeing "Created" when the file is initially created, and "Modified" once the file is being written to. But nothing related to "Closed".

Is there any way to monitor if the file is closed?

Thanks in advance!

**Comment by DonyorM** [comment]
I don't think this is possible. Programs like Microsoft word write files in an in-memory buffer. This has no interaction with the file system. When you "save" a file it either modifies or overwrites the old file with the content from the buffer. However, closing the buffer (the window) has no effect on the file system therefore cannot be detected. You're better off seeing if the program writing the file has a way for you to hook into it, and using an api call to run a method when the window closing.

**Comment by danilobellini** [comment]
If you're dealing with Linux systems, you seem to be looking for the `IN_CLOSE_WRITE` inotify event: http://man7.org/linux/man-pages/man7/inotify.7.html

**Comment by danilobellini** [comment]
This is a duplicate of #313, and would be solved by the enhancement proposal #217.

**Comment by igordavid** [comment]
Thanks - initially, we were using inotify which have IN_CLOSE_WRITE event and it worked nice. Then we switched to watchdog because of some advanced features which inotify didn't had, but then we reverted back to inotify because of no CLOSE_WRITE mechanism.

Thanks for the answers and looking forward for this implementation in watchdog.

**Comment by BoboTiG** [comment]
Finally implemented the inotify part with 2fab7c2a06df0785a322186b191d0cd7c95f566a (will be part of the 1.0.3 version).
