### ISSUE TITLE
Observer for files in first-level sub directory of given directory

### ISSUE THREAD

**Issue by ssimo3lsuhsc** [gorakhargosh/watchdog#370]
I asked this question on Google Groups a month and a half ago, but I received no response. I want to listen for changes to files in all first-level subdirectories of a given directory. I do not want to listen for changes to files at the root. I am thinking about scheduling a watch on the parent directory to schedule watches on the subdirectories as they are created. The new watches will need to be attached to the same observer or clones of the same observer. I am REALLY concerned about the effects of cloning an observer or attaching watches to it while it is running. I am doing this for a project that has a deadline of August 31, so I'd appreciate if somebody would respond before tomorrow at 8 AM Central Time. Even if you can't respond before then, I would like to know as soon as possible that somebody is reading this. Even criticism is welcome. Thank you!

Stuart

**Comment by rsjethani** [comment]
I have a simpler approach for you:
You can get a [list of first level sub directories](http://stackoverflow.com/questions/141291/how-to-list-only-top-level-directories-in-python) like:
first_level_subs = next(os.walk("path/to/your/root"))[1]

Now you can simply schedule multiple watches by simply iterating over the above list.

Hope it's not too late ;)
