### ISSUE TITLE
Constructor for OSError used incorrectly ( inotify_c.py line 406 )

### ISSUE THREAD

**Issue by ph-hs** [gorakhargosh/watchdog#377]
OS in Windows10 with "Windows Subsystem for Linux" enabled, and from inside the "Bash" shell, although it still appears to be cmd.exe.

>   File "/usr/local/lib/python2.7/dist-packages/watchdog/observers/api.py", line 255, in start
>     emitter.start()
>   File "/usr/local/lib/python2.7/dist-packages/watchdog/utils/**init**.py", line 111, in start
>     self.on_thread_start()
>   File "/usr/local/lib/python2.7/dist-packages/watchdog/observers/inotify.py", line 121, in on_thread_start
>     self._inotify = InotifyBuffer(path, self.watch.is_recursive)
>   File "/usr/local/lib/python2.7/dist-packages/watchdog/observers/inotify_buffer.py", line 35, in __init__
>     self._inotify = Inotify(path, recursive)
>   File "/usr/local/lib/python2.7/dist-packages/watchdog/observers/inotify_c.py", line 187, in __init__
>     self._add_dir_watch(path, recursive, event_mask)
>   File "/usr/local/lib/python2.7/dist-packages/watchdog/observers/inotify_c.py", line 364, in _add_dir_watch
>     self._add_watch(path, mask)
>   File "/usr/local/lib/python2.7/dist-packages/watchdog/observers/inotify_c.py", line 385, in _add_watch
>     Inotify._raise_error()
>   File "/usr/local/lib/python2.7/dist-packages/watchdog/observers/inotify_c.py", line 406, in _raise_error
>     raise OSError(os.strerror(err))
> OSError: Invalid argument

**Comment by ph-hs** [comment]
http://stackoverflow.com/a/8978153 shows what the signature for OSError is.

**Comment by deluxghost** [comment]
i think i meet the same issue, but i cant provide further infomation
