### ISSUE TITLE
New pypi release?

### ISSUE THREAD

**Issue by mafrosis** [gorakhargosh/watchdog#379]
Hi there - I just tried using the `--debug-force-polling` option added in 5388391 and found it wasn't there :)

Any chance we could get a new release pushed to pypi?

Thanks

**Comment by aseques** [comment]
It is only present when running on the log mode, I had to make some local changes in my setup so I could use watchmedo to monitor a smb mounted folder.

**Comment by JelteF** [comment]
This would be great. The latest version doesn't work on mac and also has same bugs that are fixed in te latest master. Right now I'm just installing from git instead.

**Comment by BoboTiG** [comment]
The development process and releases are on the way :)
