### ISSUE TITLE
Module not avalibe 

### ISSUE THREAD

**Issue by AlexisPotvin** [gorakhargosh/watchdog#384]
from watchdog.observers import Observer
from watchdog.events import PatternMatchingEventHandler
there is no modules Observer and PatternMatchingEventHandler.
I used pip install and also build it from source...

**Comment by DonyorM** [comment]
What's your setup? What output did the installations cause? From which directory relative to watchdog are you running this? What Python version? What is the exact error message python gives?

**Comment by AlexisPotvin** [comment]
I was using both ubuntu 16.04 and 14.04 on 2 different vm and also ubuntu 14.04 on an other computer. 
As far as the installation went everything was fine, i compiled it with python setup.py install and also did a pip install.. The installation went well no output error but when i was running the example i had the error 
    from watchdog.observers import Observer
ImportError: cannot import name Observer

I am using python 2.7.. The watchdof.observers and events module can be found but not the LoggingEventHandler and the Observer ...

**Comment by DonyorM** [comment]
Are you using a virtual environment?

**Comment by AlexisPotvin** [comment]
Yes and i figured it out it was due to multiples instance of python! it working now. Thanks for your help!

**Comment by DonyorM** [comment]
Great!
