### ISSUE TITLE
what use event id？

### ISSUE THREAD

**Issue by smartning** [gorakhargosh/watchdog#385]

**Comment by DonyorM** [comment]
I'm going to need more details if you want help.

**Comment by ixuning** [comment]
here are the moved events? They “disappeared”
This implementation does not take partition boundaries into consideration. It will only work when the directory tree is entirely on the same file system. More specifically, any part of the code that depends on inode numbers can break if partition boundaries are crossed. In these cases, the snapshot diff will represent file/directory movement as created and deleted events.

**Comment by DonyorM** [comment]
I'm still not fully sure what your issue is. What is the behavior you expect? What is the actual behavior?

**Comment by BoboTiG** [comment]
Closing as the question is not clear and old.
