### ISSUE TITLE
Using WatchDog to Spawn Processes

### ISSUE THREAD

**Issue by MikeOcc** [gorakhargosh/watchdog#388]
I am unclear as to how to access the file and directory names after they have been added/modified.  I need that information to be able to spawn independent python processes.

**Comment by DonyorM** [comment]
Do you mean you need to know the paths to the files? Or just the names of the files?

**Comment by MikeOcc** [comment]
Actually, my issue has morphed.  I am able to use watchdog to monitor file creation and trigger processes, but when I attach a directory in docker using the -v command, it doesn't seem to see or detect the file changes.

**Comment by DonyorM** [comment]
What operating system/observer are you using. I believe some of them cannot cross filesystems.

**Comment by rrzaripov** [comment]
@BoboTiG I think we can close this issue, because not additional information for it reproduce issue was be appended.
