### ISSUE TITLE
Event handlers ignore existing subdirectories

### ISSUE THREAD

**Issue by tiamunley** [gorakhargosh/watchdog#389]
recursive=True works for all subdirectory structures that are new to my base path, but if those subdirectories already exist when starting a watchdog they are not considered events.

e.g.

Input path: /path/to/dir/
Subdir: /path/to/dir/dir1/dir2/
File: /path/to/dir/dir1/dir2/file.txt

Doesn't pick up file file.txt if dir1/dir2 already existed before running watchdog script

**Comment by DonyorM** [comment]
What python version are you using? What operating system?

**Comment by tiamunley** [comment]
I'm so sorry, this was my own error. I'm sorry I didn't close this ticket.
