### ISSUE TITLE
on_moved never works on Windows

### ISSUE THREAD

**Issue by nitinmht** [gorakhargosh/watchdog#393]
any file being moved into sub directories of directory being watched always comes up with multiple events - deleted, created, modified and never hits moved event.

**Comment by michaelPf85** [comment]
I suppose it's a limitation from the underlying Windows API (ReadDirectoryChangesW , according to this : [https://pypi.python.org/pypi/watchdog](url)).

When you look at the Windows documentation, it looks like there is no event like "moved" : [https://msdn.microsoft.com/en-us/library/windows/desktop/aa365465(v=vs.85).aspx](url). Only renames in the same folder can be detected, NTFS seems to manage a move like a copy from the user point of view.

**Comment by BoboTiG** [comment]
@michaelPf85 is right, there is no suh event on Windows. You will have to take care of them manually.
