### ISSUE TITLE
doesn't work on distributed file system:  should be able to override observer implementation.

### ISSUE THREAD

**Issue by petersilva** [gorakhargosh/watchdog#395]
Using watchdog on a cluster using IBM General Parallel File System.  The processes writing the files are doing so on one node, and the watchdog is setting the watches on another node.   The inotify events are not gettting to the watcher, so the directory is filling up, and the watch is never triggering.  The current
implementation chooses the observer based on kernel/platform.  Many networks file systems do not support the same facilities as local ones.  I don't think watchdog can fix this, but it should provide the ability to override the platform 'best' observer with other available implementations for cases.

**Comment by DonyorM** [comment]
It is very much possible to initiate your own observer. Simply create an instance of the specific observer rather than the Observer class.

So something like
```
from watchdog.observers import InotifyObserver

observer = InotifyObserver()
//Your code as needed
```

**Comment by petersilva** [comment]
It´s true.  In my applicaiton I let it pick the optimal one by default, and added a polling option to pick the pollingObserver if needed.
