### ISSUE TITLE
Observer fails on Ubuntu Subsystem for Windows

### ISSUE THREAD

**Issue by acerberus** [gorakhargosh/watchdog#398]
The generation of an observer fails when running python within the [Ubuntu Subsystem for Windows](https://msdn.microsoft.com/de-de/commandline/wsl/about#). As an example, use the observer example code:

```
import sys
import time
import logging
from watchdog.observers import Observer
from watchdog.events import LoggingEventHandler

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO,
                        format='%(asctime)s - %(message)s',
                        datefmt='%Y-%m-%d %H:%M:%S')
    path = sys.argv[1] if len(sys.argv) > 1 else '.'
    event_handler = LoggingEventHandler()
    observer = Observer()
    observer.schedule(event_handler, path, recursive=True)
    observer.start()
    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        observer.stop()
    observer.join()
```

This fails with: OSError: Invalid argument.

Probably, this is to be expected as the platform check returns Linux while the underlying filesystem is a Windows system. Anyways, it would be fantastic if this could be detected automatically somehow.

**Comment by rrzaripov** [comment]
@BoboTiG can be closed, because no additional information obtained.
