### ISSUE TITLE
Observer fails on Mac OS if check 

### ISSUE THREAD

**Issue by xiva-wgt** [gorakhargosh/watchdog#402]
Wrong special files found in mac os.
```python
observer.schedule(fs_event_handler, '/', recursive=True)
for _ in walk(path):
  File "/Library/Python/2.7/site-packages/watchdog-0.8.3-py2.7-macosx-10.12-intel.egg/watchdog/utils/dirsnapshot.py", line 213, in walk
    paths = [os.path.join(root, name) for name in listdir(root)]
OSError: [Errno 20] Not a directory: '/Volumes/Macintosh HD/dev/fd/5'
```
You may need to add a check for error ENOTDIR to
https://github.com/gorakhargosh/watchdog/blob/master/src/watchdog/utils/dirsnapshot.py#L218

1. From project basket-lib, under directory packages/mercurial/mercurial, in source file windows.py. 
handle directory not found in Python version prior to 2.5
Python <= 2.4 returns native Windows code 3 in errno
Python >= 2.5 returns ENOENT and adds winerror field
EINVAL is raised if dir is not a directory.
`if e.errno in (3, errno.ENOENT, errno.EINVAL, errno.ENOTDIR):`

2. `if e.errno == errno.ENOENT or e.errno == errno.ENOTDIR :`

Sorry for my English

**Comment by BoboTiG** [comment]
Closing as it was fixed with the commit 19eb494dce9fc01c9821a0b909755c3cca94593f.
