### ISSUE TITLE
Run shell command at the beginning?

### ISSUE THREAD

**Issue by ChillarAnand** [gorakhargosh/watchdog#406]
One of the best use of watchmedo is restarting a process when a file changes. For example, celery worker can be killed and started again using

    watchmedo shell-command --patterns="*.py" --recursive --command='pkill celery; celery worker -l info -A t' 

Unfrotuantely, this won't start the process until there is an event. It would be helpful if watchmedo has a flag to make the command run at the start.

**Comment by clems4ever** [comment]
Hello @ChillarAnand , why did you close this issue? Is there any way to do that already?

**Comment by clems4ever** [comment]
Found it! `auto-restart` command is the way to go.
