### ISSUE TITLE
where should I change default installation directory

### ISSUE THREAD

**Issue by CarlYohoo** [gorakhargosh/watchdog#407]
Hello ,as mentioned above, I want to install in code, but I have no authority to use '/usr/lib/python2.7/site-packages/test-easy-install-24370.write-test' . 
And I can't find where to change it ..

**Comment by CarlYohoo** [comment]
I am very sorry to distub you ... @tommorris @pilt @senko @novas0x2a @peritus

**Comment by novas0x2a** [comment]
@CarlYohoo you probably should be [using a virtualenv](https://www.dabapps.com/blog/introduction-to-pip-and-virtualenv-python/).

**Comment by BoboTiG** [comment]
You will find your answer here: https://stackoverflow.com/a/7143496/1117028

I am closing the ticket as it is not related to watchdog.
