### ISSUE TITLE
Watching mounted drives

### ISSUE THREAD

**Issue by alt3red** [gorakhargosh/watchdog#409]
Is there a way to use watchdog for watching a shared mounted network drive in linux and report when someone else on the network copies files to that folder?

Thank You!

**Comment by peci1** [comment]
It depends. 

- [NFS should not work with inotify](https://stackoverflow.com/questions/4231243/inotify-with-nfs)
- Samba (CIFS) does not work with inotify (my own experience)
- SSHFS does not work with inotify (my own experience)

So, to conclude, you're out of luck unless you want to write the inotify broker mentioned in the SO answer.

A side note: At PyPi index, there is a section with Caveats. I haven't found anything about network drives there, though it should be mentioned there in my view.

 should not work with inotify

**Comment by seanpompea** [comment]
@alt3red -- Yes, use `PollingObserver`. 

More info: https://pythonhosted.org/watchdog/api.html?highlight=observedwatch#watchdog.observers.polling.PollingObserver

**Comment by BoboTiG** [comment]
Closing as there is a note in the README.
