### ISSUE TITLE
Mac issue installing watchdog caused by compilation error in Apple sources

### ISSUE THREAD

**Issue by paul-hammant** [gorakhargosh/watchdog#422]
```
/usr/include/hfs/hfs_format.h:794:2: error: unknown type name 'uuid_string_t'; did you mean 'io_string_t'?
        uuid_string_t   ext_jnl_uuid;
        ^
```
This would happen whether I was using a pip2 or pip3 to install watchdog. It would also happen if I downloaded the source tarball and followed the instructions on the watchdog site.

The fix:

```
sudo mv /usr/local/include/uuid/uuid.h /usr/local/include/uuid/uuid.h.bak
```

^ A user can always rename it back again after they've successfully installed watchdog.

Maybe the watchdog installer could trap for this error, and suggest something helpful to the user.

**Comment by BoboTiG** [comment]
Same symptoms as #450. This is not the job of watchdog to handle that error. In fact, it does not have any power at this level.

**Comment by paul-hammant** [comment]
Not the job of Watchdog, no, but maybe the job of watchdog **installer**
