### ISSUE TITLE
Blocks deleting the watched directory

### ISSUE THREAD

**Issue by pzzp** [gorakhargosh/watchdog#425]
On Windows.

If I delete the watched directory before any event,  the result:
![image](https://user-images.githubusercontent.com/21138299/32486362-623bcc2a-c3e1-11e7-97da-1d03c21c8047.png)
If I delete it after some event,  the program will get stuck.

**Comment by BoboTiG** [comment]
Should be fixed by #572, right @rrzaripov?

**Comment by rrzaripov** [comment]
@BoboTiG yes this is same issue.
