### ISSUE TITLE
some wrong with directory and FileDeletedEvent

### ISSUE THREAD

**Issue by LaurenSUIYUE** [gorakhargosh/watchdog#429]
![image](https://user-images.githubusercontent.com/25794273/34095472-8628ecda-e40c-11e7-91a5-2cd6d103bf02.png)

![image](https://user-images.githubusercontent.com/25794273/34095452-715bcc3c-e40c-11e7-8eee-3d2d575d4652.png)

when i new a directory and changed its name, it works. But when i delete it, the event is  FileDeletedEvent. 
It confused me. Please help me to solve it.

**Comment by steinirey** [comment]
I just stumbled upon this issue as well. Deletion of directories emits FileDeleteEvent not DirDeleteEvent.

**Comment by fedexist** [comment]
Same issue here, I was expecting a DirDeleteEvent but a FileDeleteEvent gets dispatched instead. Might be an issue on Windows, as I tried on a Linux machine and it works correctly.

**Comment by BoboTiG** [comment]
This is specific to Windows where we cannot know if a deleted event is about a folder or a file. There is simply no way exposed by `ReadDirectoryChangesW`, sadly :/
