### ISSUE TITLE
Can not make it work with usbmount

### ISSUE THREAD

**Issue by vivekanand1101** [gorakhargosh/watchdog#431]
I am trying to automate the mounting + detecting a pendrive using [usbmount](https://github.com/rbrito/usbmount) and python-watchdog but, i am not able to make it work. Usbmount is able to detect the pendrive and it is mounted at the correct place (/media/usb). I can see the files using ```ls``` but, i expected python-watchdog to detect the "creation" or "modified" event which is not happening. I am using [FileSystemEventHandler](https://github.com/gorakhargosh/watchdog/blob/master/src/watchdog/events.py#L309)

**Comment by Rocking80** [comment]
I got the same issue. Seems watchdog cannot detect changes which not happen on local system.

**Comment by xandriaw** [comment]
I am having a similar issue with an NFS mount (inside docker). Seems like it doesn't detect the file creation there either :( . If I then copy from inside the machine where python is running to itself, then the file is detected.

**Comment by danilobellini** [comment]
This seems to be an environment/OS issue, not a watchdog one.

Are you all using the `PollingObserver` or the default `Observer`? Are you all using Linux? If yes, which Linux?

From the mount point and the "NFS in Docker", I think you're all on Linux using the inotify observer on a FUSE or network-based file system that has no kernel support for inotify. That means the application can't rely on inotify.

If that's what's going on, there's nothing in this project that could be done: you need to either use the polling observer in the application code, or fix this issue upstream (Linux kernel? inotify? Some driver?) to work with those file systems.
