### ISSUE TITLE
UPDATE PYPI

### ISSUE THREAD

**Issue by jacobthetechy** [gorakhargosh/watchdog#434]
I'm working on a project that mounts and watches files over the network. If for any reason I loose connection, which is normal. I get a error in the thread and it stops the program. After digging around I found that the master is not the same version that is on pypi. For instance the updated code that would save my program from hanging.  [ https://github.com/gorakhargosh/watchdog/commit/cb70f70aab9bb3dbdfe473cfe62ff4461aa800fd](https://github.com/gorakhargosh/watchdog/commit/cb70f70aab9bb3dbdfe473cfe62ff4461aa800fd)
Could you please update the pypi with the latest version of your code.

**Comment by danilobellini** [comment]
Updated! The commit from your link is part of the v0.9.0. If you're still getting that thread error, please open a new issue.
