### ISSUE TITLE
OverflowError: Sleep length is too large

### ISSUE THREAD

**Issue by Paingg** [gorakhargosh/watchdog#435]
I'm working on a project that tracks and reads a file. The script has been running for months nicely, but recently I encountered an unknown error "OverflowError: Sleep length is too large". On the error logs, the error was triggered at line 360 from watchdog/src/watchdog/observers/api.py.
It would be great if someone can help me out with the possible causes of that error and how to deal with that. Thanks in advance.

**Comment by BoboTiG** [comment]
The error was likely triggered from https://github.com/gorakhargosh/watchdog/blob/d33bee0290e00ecb3570dd938db72a2550933586/src/watchdog/utils/delayed_queue.py#L66

There may be a better implementation of this loop, if truse  A test car would be nice to start.

**Comment by BoboTiG** [comment]
@Paingg did you encounter the issue again since then? It will be hard to tackle without more details.
