### ISSUE TITLE
How to run watchdog simultaneoulsy when i start a flask webservice ? 

### ISSUE THREAD

**Issue by MLDSBigGuy** [gorakhargosh/watchdog#440]
I have a flask web application. Upon user requests, i am monitoring some log files. Whenever i start the webservice, watchdog also need to start. 

Currently, i am writing a seperate webservice just to start watchdog. Is there any simplier way to do this ? 

I have to dockerizing my application. My CMD/Entrypoint can be only one service. 

Any ideas ? 

Thank you,

**Comment by hdiogenes** [comment]
This is not an issue with the `watchdog` library, but a programming question that would fit much better on stackoverflow.com than here (and that also would make it have a much greater chance of being answered). Could you please post your question there?
