### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by bauripalash** [gorakhargosh/watchdog#448]
Last commit is about 1years old.

**Comment by ddierkes** [comment]
136 open issues...

**Comment by jacopostyleshoots** [comment]
141 issues in August 28, 2018. No active forks?

**Comment by danilobellini** [comment]
I've just became a new collaborator. I'm going to release today a new 0.9.0 version with the master tip as is (actually, I'll change some few stuff like adding me to AUTHORS and adding a 3.7 classifier).

**Comment by bauripalash** [comment]
I think it would be good idea to end Support for Python 2.
Python 3.4, 3.5 and 3.6 would be enough

**Comment by danilobellini** [comment]
I managed to make it pass on every Python version (Python 2.6+, Python 3.2+, PyPy, PyPy3) on Travis CI!

https://travis-ci.org/gorakhargosh/watchdog/builds/421748950

**Comment by argosvr** [comment]
"I think it would be good idea to end Support for Python 2."
Very bad idea... for a question of using certain libs, you need to be compatible with Python 2.7

**Comment by danilobellini** [comment]
The new v0.9.0 had just been released and it's already available in PyPI! I'll close this issue =)
