### ISSUE TITLE
conftest.py missing from PyPI tarball

### ISSUE THREAD

**Issue by felixonmars** [gorakhargosh/watchdog#471]
Running the tests from a PyPI tarball fails with "E       fixture 'p' not found", because conftest.py is missing from it. It would be nice to add it to the PyPI tarball.

**Comment by BoboTiG** [comment]
Closed with 7a66c5f0.

**Comment by glaubitz** [comment]
Thanks for the fix! Could you also release a new upstream version so the fix actually gets propagated to PyPi?

I just had to cherry-pick this patch for the package in openSUSE Factory to build properly.

**Comment by BoboTiG** [comment]
Will be handled very soon (#485) :)
