### ISSUE TITLE
`Modified Event` were not triggered when file size has changed of `PollingObserver` or  `PollingObserverVFS`

### ISSUE THREAD

**Issue by QuantumEnergyE** [gorakhargosh/watchdog#499]
`PollingObserver` works well in most cases.
When `dd` commands were executed on `cephfs`, file size were changed, but `Modified Event` could not be triggered. 
command: ```dd if=/dev/zero of=test count=1 bs=1G```
I looked at the filesystem and found that the modified time of the file would not change during `dd`. This problem is found only when the count parameter of the `dd` command is 1 on `cephfs`.
I recommend add the judgment of file size of `Modified Event`.

**Comment by BoboTiG** [comment]
Closed via f313e9deb0027d39a5ff82a315e7150669de41b5.
