### ISSUE TITLE
Works fine once or twice then nothing happens

### ISSUE THREAD

**Issue by peterbe** [gorakhargosh/watchdog#50]
I'm on OSX and it's using the kqueue observer. I start it something like this:

```
watchmedo shell-command --patterns="*.py" --recursive  \
  --command="./manage.py test" apps/
```

It starts, I change a file and save and the shell command runs; and I notice my unit test failed. I change the file again and save but this time nothing happens with watchmedo. 

Sometimes it works a second time and even a third I've seen but never more than that.

**Comment by danilobellini** [comment]
Watching a directory with a file named tox.ini, I did a `touch tox.ini`, and the only event emitted was

```
File modified: tox.ini
```

Saving with a `:w` in vim, I've got:

```
File created: tox.ini
File deleted: tox.ini
```

The word I'm printing is the `event_type` attribute, and `File` just means the `is_directory` is `False`.

I thought that should be solved by looking for a match between a delete and a create, but it doesn't seem enough, as it appeared reversed here.
