### ISSUE TITLE
TestCase failed of python3.4.

### ISSUE THREAD

**Issue by QuantumEnergyE** [gorakhargosh/watchdog#500]
INTERNALERROR>     warnings.warn(warning, stacklevel=2)
INTERNALERROR> _pytest.warning_types.RemovedInPytest4Warning: MarkInfo objects are deprecated as they contain merged marks which are hard to deal with correctly.

**Comment by rrzaripov** [comment]
@QuantumEnergyE this is because tests running with latest pytest, but pytest-timeout used for Python 3.4 is < 1.2.1. So, if run tests with pytest < 3.3 test will pass.
