### ISSUE TITLE
How to get 0KB file open event?

### ISSUE THREAD

**Issue by wwling2001** [gorakhargosh/watchdog#502]
Hi 
i work on my paper to suspect filesystem file event. Such as file move, modify, delete and so on. Watchdog can most function i needed. And coding with Watchdog. But i found that 0KB file open event can not be monitor. Has anybody met this problem? or any suggestion is welcome.

Thanks.

**Comment by rrzaripov** [comment]
As I know currently watchdog not support file open event (full list of supported events here). For Linux platform inotify supports IN_OPEN event, so it is possible to handle it in watchdog. But for Windows no such event.

**Comment by wwling2001** [comment]
@rrzaripov Thank you!  i will goging on working on this subject. Try other ways.

**Comment by rrzaripov** [comment]
@BoboTiG this issue can be closed.
