### ISSUE TITLE
Can I watch files created on NFS using watch dog observer?

### ISSUE THREAD

**Issue by swaapnika-guntaka** [gorakhargosh/watchdog#504]
I created a simple FileSystemEventHandler to watch for new files. However when I specify an NFS share location it doesnt trigger any event. 

Can watchdog observer for file events on NFS? 
```
/remote/nfs/testdir/<file> -  Doesn't work
/SCRATCH/testdir/<file> - Works

```

`#!/usr/bin/env python3
import sys
import time
import logging
# watchdog
from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler

class Watcher:
    """
    Watch for events
    """

    def __init__(self, path):
        """
        Watch specified path for changes
        """
        self.path = path
        print(path)
        self.observer = Observer()

    def watch(self):
        """
        watch function to watch for events
        """
        print(self.path)
        event_handler = Handler()
        self.observer.schedule(event_handler, self.path, recursive=True)
        self.observer.start()
        try:
            while True:
                print("watching")
                time.sleep(5)
        except BaseException:
            self.observer.stop()
            print("Error")
        self.observer.join()

class Handler(FileSystemEventHandler):

    @staticmethod
    def on_any_event(event):
        print(event)
        if event.is_directory:
            return None
        elif event.event_type == 'created':
            # Take any action here when a file is first created.
            print("Received created event - %s." % event.src_path)
        elif event.event_type == 'modified':
            # Taken any action here when a file is modified.
            print("Received modified event - %s." % event.src_path)

if __name__ == "__main__":
    watcher = Watcher("/SCRATCH/testwatch")
    watcher.watch()`

**Comment by QuantumEnergyE** [comment]
You need to use `PollingObserver`. 

```
import sys
import time
import logging
from watchdog.observers.polling import PollingObserver
from watchdog.events import LoggingEventHandler

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO,
                        format='%(asctime)s - %(message)s',
                        datefmt='%Y-%m-%d %H:%M:%S')
    path = sys.argv[1] if len(sys.argv) > 1 else '.'
    event_handler = LoggingEventHandler()
    observer = PollingObserver()
    observer.schedule(event_handler, path, recursive=True)
    observer.start()
    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        observer.stop()
    observer.join()
```

**Comment by swaapnika-guntaka** [comment]
Yes that worked
