### ISSUE TITLE
Make able to view build results on appveyor.com

### ISSUE THREAD

**Issue by rrzaripov** [gorakhargosh/watchdog#512]
@gorakhargosh currently, link on badge with build status for Windows give us:

![image](https://user-images.githubusercontent.com/6154870/51468292-a357c080-1d7f-11e9-87f5-3355fb479e9f.png)

By default, on appveyor.com nobody except owner can't see build results. For fix it, need to switch on "view" option for users.

![image](https://user-images.githubusercontent.com/6154870/51467921-c46be180-1d7e-11e9-9232-8ee68b3d7565.png)

P.S. And how about add appveyor to PR check (like a travis)?

Thanks!

**Comment by rrzaripov** [comment]
Travis now [supporting](https://docs.travis-ci.com/user/reference/windows/) Windows, maybe just rework to using only travis without appveyor?

**Comment by BoboTiG** [comment]
Why not? I am +1 if we can finally have public status on Windows :+1:

**Comment by BoboTiG** [comment]
I think we can remove all AppVeyor stuff now. Do you mind opening a PR or I can do that?

**Comment by rrzaripov** [comment]
@BoboTiG yes, we can remove this stuff, close issue and remove red badge in README.rst, Can you create PR for this? I am will be little busy in near time.

**Comment by rrzaripov** [comment]
@BoboTiG BTW please fix double https:// in changelog link in README.rst, I've overlooked it🤦‍♂️

**Comment by BoboTiG** [comment]
Will be done right now :+1:
