### ISSUE TITLE
Events from non-ASCII paths raise UncodeDecodeError

### ISSUE THREAD

**Issue by exarkun** [gorakhargosh/watchdog#516]
```
from os import mkdir
from watchdog.observers.inotify import InotifyObserver
from watchdog.events import FileSystemEventHandler

class H(FileSystemEventHandler):
    def on_any_event(self, event):
        print(event)

def main():
    d = u"demo"
    handler = H()

    mkdir(d)
    obs = InotifyObserver()
    obs.schedule(handler, d, recursive=True)
    obs.start()
    mkdir(u"/".join((d, u"\N{SNOWMAN}")))
    obs.join()

main()
```

results in this exception

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "watchdog/src/watchdog/observers/inotify_buffer.py", line 87, in run
    inotify_events = self._inotify.read_events()
  File "watchdog/src/watchdog/observers/inotify_c.py", line 324, in read_events
    inotify_event = InotifyEvent(wd, mask, cookie, name, src_path)
  File "watchdog/src/watchdog/observers/inotify_c.py", line 478, in __init__
    self._name = name.decode()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)
```

Apparently introduced in 0c5e3531748d231e34ef6ecf8581ac20fd956b25

**Comment by BoboTiG** [comment]
Python 2 is no more supported. Do you reproduce the error on Python 3?

**Comment by exarkun** [comment]
> Python 2 is no more supported. Do you reproduce the error on Python 3?

That's quite disappointing and frustrating to discover, considering the README:

> Works on Python 2.7 and 3.4+. If you want to use an old version of Python, you should stick with watchdog < 0.10.0.

My project is a large Python 2 code base and there's zero chance I will be using Python 3 with it in the next year months (maybe slightly higher than zero chance after that).  It's 70kloc of messy code with un-ported dependencies.

Is there no way the watchdog project can continue to support Python 2 at least until python-dev abandons it?  (And note that even after python-dev abandons Python 2, there's still PyPy.)

If you're dead set on dropping Python 2 then as a huge favor to your users, I suggest changing the README to stop advertising Python 2.7 support.

**Comment by BoboTiG** [comment]
Ooops sorry ! I said bullshit: Python 2.7 is still supported. I dropped support on aonther project and mixed my brain :/

For the bug, it would be great if you can have a look for a PR (including a simple test).

**Comment by exarkun** [comment]
Okay, thanks!  I'll see about putting together a PR tomorrow.
