### ISSUE TITLE
Allow a custom event mask to be specified for use with the Linux inotify observer

### ISSUE THREAD

**Issue by exarkun** [gorakhargosh/watchdog#520]
If I want to use watchdog as a Python library and I want to receive events other than the ones that watchmedo is interested, I have to jump through a bunch of hoops to get an `InotifyObserver` which will set or clear values in the event mask given to `inotify_c.Inotify`.

I want to be able to supply my own mask to `InotifyObserver` so that I can receive these other events without monkey-patching the watchdog implementation.

An example of an acceptable interface would be:

```
InotifyObserver(event_mask=my_integer_mask)
```

Another example that might provide better flexibility would be:

```
InotifyObserver(emitter_class=MyInotifyEmitterClass)
```

coupled with the necessary changes to `InotifyBuffer` so that it passes through an event mask argument, eg

```
InotifyBuffer(path, recursive, event_mask=my_integer_mask)
```

with `event_mask` being passed on to the `inotify_c.Inotify` instance it creates.

Note that the `emitter_class` parameter is a generalization of an idea already present in the code (`generate_full_events` - which is essentially just a parameter to control the behavior of the emitter and the observer doesn't otherwise need to know anything about it).

**Comment by BoboTiG** [comment]
The feature was done in #989. I'll cut a new release "quite soon" :)
