### ISSUE TITLE
Watchdog does not provide the extra watchmedo

### ISSUE THREAD

**Issue by apnewberry** [gorakhargosh/watchdog#523]
The docs say 
```
$ python -m pip install watchdog[watchmedo]

```

but when I do that, I get this message
```
$ venv/bin/pip install 'watchdog[watchmedo]'
Collecting watchdog[watchmedo]
  watchdog 0.9.0 does not provide the extra 'watchmedo'

```
Pip 19.0.1
Python 3.6.5
Ubuntu 18.04

**Comment by rrzaripov** [comment]
@apnewberry watchmedo will be extra in next release. Version 0.9.0 [released](https://github.com/gorakhargosh/watchdog/releases/tag/v0.9.0) 28 Aug 2018, date of [commit](https://github.com/gorakhargosh/watchdog/commit/a37e1ae1503f6c8c2a88cffe76c74012af23c9f9) that make watchmedo extra is 12 Jan 2019.

**Comment by BoboTiG** [comment]
It will be part of the next version :)
The `master` branch follows the current development version, so there is a small difference for now.
