### ISSUE TITLE
Sending repeated SIGINT (Ctrl-C) signals to watchmedo auto-restart exits without stopping the child process

### ISSUE THREAD

**Issue by bengotow** [gorakhargosh/watchdog#543]
Hey folks! I've been using the watchmedo CLI to make a web server automatically restart when the contents of a directory change. Unfortunately we ran in to issues with this pretty quickly after launch because sending a SIGINT to `watchmedo`:

1) Cleans up the file observers
2) Sends a SIGINT to the child process

Step 1 takes about 500ms (at least on large directories like the one we're watching) and sending a second SIGINT in that time frame kills watchmedo without a SIGINT ever getting sent to the child. 

If you're one of those keyboard bashing folks that hammers Ctrl-C, watchmedo basically never stops the child process when you kill it.

We've implemented a fix for this over here (https://github.com/dagster-io/dagster/pull/930) that involves calling `event_handler.stop()` before cleaning up the file observers here: https://github.com/gorakhargosh/watchdog/blob/master/src/watchdog/watchmedo.py#L124. This might have undesirable side effects when `observe_with` is used in other modes (I'm not sure?) but it ensures that the child process is killed as soon as watchmedo receives a signal and it doesn't leave dangling processes.

Would a PR for this be mergeable?

**Comment by BoboTiG** [comment]
Hello @bengotow,

Thanks for opening the issue. I think a Pr would be mergeable, yes :)
