### ISSUE TITLE
Fix test_emitter.py::test_recursive_off() on Windows

### ISSUE THREAD

**Issue by BoboTiG** [gorakhargosh/watchdog#548]
Fix `test_emitter.py::test_recursive_off()` on Windows.

**Comment by rrzaripov** [comment]
@BoboTiG I've check test run result in appveyor but not found any failed test_emitter.py::test_recursive_off() (except Python 3.4 - it's just total broken). Can you give me any pytest backtrace?

**Comment by BoboTiG** [comment]
Oh, this is a good thing then. It must be my VM which is in a poor state :)
Thanks for taking time to check!
