### ISSUE TITLE
Support SIGUSR1 and SIGUSR2 in auto-restart --signal

### ISSUE THREAD

**Issue by jtrakk** [gorakhargosh/watchdog#549]
`SIGUSR1` and `SIGUSR2` aren't supported because [the regex](https://github.com/gorakhargosh/watchdog/blob/master/src/watchdog/watchmedo.py#L534) in watchmedo doesn't match them. 

```python

    if re.match('^SIG[A-Z]+$', args.signal):
        stop_signal = getattr(signal, args.signal)
```

**Comment by BoboTiG** [comment]
Hello @jtrakk,

Thanks for the report, it is now fixed in the `master` branch :)
