### ISSUE TITLE
Another cross-platform file system monitor in Python

### ISSUE THREAD

**Issue by wimleers** [gorakhargosh/watchdog#55]
Hi,

I just wanted to ping you since I'm the founder/developer of [File Conveyor](http://fileconveyor.org) (code [on github](https://github.com/wimleers/fileconveyor)), for which I developed something similar to `watchdog`, called `FSMonitor`.

It's also cross-platform (but only supports `inotify` and `FSEvents`). It's far less documented or developed than `watchdog` though. It dates back to [April 15, 2009](https://github.com/wimleers/fileconveyor/commit/647210a25cc82ff7f485d463ba2a058adee91a7f), i.e. long before `watchdog` existed. The fact that I did an extremely poor job of making File Conveyor's components separately visible is probably why you never found it.

Recently, File Conveyor has become very active again. Today, I stumbled upon `watchdog`. After the first stable release (1.0) of File Conveyor, I'd like to switch to `watchdog`, because I obviously can gain from this far more actively developed component :)

I opened a ticket in my issue queue at wimleers/fileconveyor#77.

**Comment by BoboTiG** [comment]
:+1: :)
