### ISSUE TITLE
Move to use pathlib instead of os.path and pathtools

### ISSUE THREAD

**Issue by rrzaripov** [gorakhargosh/watchdog#556]
This issue created for discuss about moving to use [pathlib](https://pathlib.readthedocs.io/en/pep428/#).
I have a next questions about this: 

- [pathtools ](https://github.com/gorakhargosh/pathtools) last updated in 2016, can pathlib replace it?
- pathlib is a part of CPython from version 3.4 and available for version 2.7 as additional package (but 2.7 support dropping in next year, so this is not so critical). And if answer on the first question is yes, we decrease count of dependencies.
- in pathlib path is a object, not a string as in os.path. No more think about encodings, it is "bytes" or "str", os.path.sep, startswith and etc.

Also, I want to know, maybe any potential problems for moving to pathlib? What youre think about this?

**Comment by chrahunt** [comment]
We should also check [pathlib2](https://pypi.org/project/pathlib2/), which is a more recently updated version of the same.

**Comment by bstaletic** [comment]
Watchdog uses only three things from `pathtools`:

1. `absolute_path()` which does `os.path.abspath(os.path.normpath())`. Can be replaced with `Path.resolve()`.
2. `filter_paths()` in the tests and `match_any_paths()` in events.py.

Here's how the latter two look like done with `pathlib`:

```python
from pathlib import PureWindowsPath, PurePosixPath

def _match_path(path, included_patterns, excluded_patterns):
  common_patterns = included_patterns & excluded_patterns
  if common_patterns:
    raise ValueError(f'conflicting patterns `{common_patterns}` included and excluded')
  return (any(path.match(p) for p in included_patterns) and
          not any(path.match(p) for p in excluded_patterns))


def filter_paths(paths, included_patterns = None, excluded_patterns = None, case_sensitive = True):
  included = ["*"] if included_patterns is None else included_patterns
  excluded = [] if excluded_patterns is None else excluded_patterns

  for path in paths:
    p = PurePosixPath(path) if case_sensitive else PureWindowsPath(path)
    if _match_path(p, set(included), set(excluded), case_sensitive):
      yield p


def match_any_paths(paths, included_patterns = None, excluded_patterns = None, case_sensitive = True):
  included = ["*"] if included_patterns is None else included_patterns
  excluded = [] if excluded_patterns is None else excluded_patterns

  for path in paths:
    p = PurePosixPath(path) if case_sensitive else PureWindowsPath(path)
    if _match_path(p, set(included), set(excluded), case_sensitive):
      yield p
```

As for the `os.path` module:

os.path | pathlib.Path
--- | ---
`join()` | Just pass arguments to the constructor
`exists()` | `exists()`
`isdir()` | `is_dir()`
`islink()` | `is_symlink()`
`dirname()` | `parent`

After that, there would only be two cases of `startswith` and two cases of `endswith`.

**Comment by bstaletic** [comment]
Here's my first attempt at switching to pathlib: https://github.com/bstaletic/watchdog/commit/35feb63de1e10de0e07f19f341bfedbf28cba435

If there's actual interest, I can make a pull request.

**Comment by BoboTiG** [comment]
Nice! Go ahead for a PR, we just dropped the Python 2.7 support so your changes will work directly.

Think to "backport" docstrings and doctests from the original `pathtools` source code.
