### ISSUE TITLE
on_deleted does not raise recursively events for each file, dir

### ISSUE THREAD

**Issue by cr3a7ure** [gorakhargosh/watchdog#561]
On Windows 10, python 3.6

When I add files, on_created fires for every file/directory recursively.
But when i remove a folder, on_deleted does not fire, except for the parent directory.
Edit:
It emits a FileDeletedEvent instead of DirDeletedEvent

**Comment by BoboTiG** [comment]
Yes, this is a known limitation of the windows API. (duplicate of #429)
