### ISSUE TITLE
Make it clear that Python 3 is supported on pythonhosted

### ISSUE THREAD

**Issue by mborus** [gorakhargosh/watchdog#565]
Hi, the project documentation on

https://pythonhosted.org/watchdog/installation.html
has a copyright message of 2010 and doesn't mention Python 3

This comes up as one of the first google search results for
"python watchdog" and makes the project look like abandoned software.

Updating the year and mentioning Python 3 would fix this.

The git repository has newer docs and mentions Python 3, so it just needs updating.

**Comment by rrzaripov** [comment]
@BoboTiG please close this, I've forget "closes" before issue id in #591🤦‍♂️
