### ISSUE TITLE
Fix documentation inconsistencies, README, ...

### ISSUE THREAD

**Issue by telenieko** [gorakhargosh/watchdog#568]
Hi,

There are two documentation sites available that I saw online:

- [pythonhosted.org](https://pythonhosted.org/watchdog/) which is crearly outdated as it is on 0.8.2, which you could not notice unless you check PyPI or github and notice that 0.9.0 is the latest release. This is also linked from that [watchdog3](https://pypi.org/project/watchdog3/) fork.
- [readthedocs.org](https://watchdog.readthedocs.io/en/latest/index.html) introduced in 2013 which does not state any version number and has a 2010 copyright notice. But the title tag says 0.6.0, so also outdated.

So... it appears there's no current documentation build out there.

#410 (2017) proposed to migrate to ReadTheDocs which was actualy done in PR #137 (in 2013!). The issue could be closed as invalid as it is done already. But maybe the README link to documentation should be updated. Or close as wontfix and revert PR #137.

So, regardless of the approach:

- The README should link to the correct documentation build,
- the incorrect one should be taken down to avoid confusion
- documentation shall be updated to the latest release

Last but not least: #565 complains about documentation not stating python 3 support, which could be closed once the above is fixed.

On a side note, I mention this here because the [watchdog3](https://github.com/nuxeo/watchdog3) repository is read-only: a request should be put to Nuxeo to push a new release to PyPI so the package package gets updated with the new README (which states the project is unmaintained), otherwise you get a first impression that watchdog does not support python3.

**Comment by rrzaripov** [comment]
@danilobellini We can close this issue? #410 and #565 was already fixed.
