### ISSUE TITLE
Ask Nuxeo to update their PyPI listing of watchdog3

### ISSUE THREAD

**Issue by telenieko** [gorakhargosh/watchdog#569]
Coming from #568 

> On a side note, I mention this here because the [watchdog3](https://github.com/nuxeo/watchdog3) repository is read-only: a request should be put to Nuxeo to push a new release to PyPI so the package package gets updated with the new README (which states the project is unmaintained), otherwise you get a first impression that watchdog does not support python3.

As that fork is archived and can be edited, I open this issue only with the purpose of citing @LKleinNux and @BoboTiG whom did the last commit on that repository with the hopes they will see this request:

Please push a new release of watchdog3 to PyPI so the README file listed there gets updated with the warning of the project being unmaintained. Thanks!

**Comment by BoboTiG** [comment]
Hello @telenieko,

This is done :+1:
