### ISSUE TITLE
Can you release a new version on PyPi?

### ISSUE THREAD

**Issue by epicfaace** [gorakhargosh/watchdog#580]
The last version was in 2018 and there seem to have been a lot of changes since then...
Thanks!

Also, what does the readme mean when it says "If you want to use an old version of Python, you should stick with watchdog < 0.10.0."? The latest version is 0.9.0.

**Comment by BoboTiG** [comment]
The README on master is the development branch. So it refers to the current dev version, which is > 0.9.0 and which dropped support for old Python versions.

The new release is tracker in #485 ;)

**Comment by epicfaace** [comment]
Ok, thanks!
