### ISSUE TITLE
For large sized files, 'FileCreatedEvent' is not waiting till the file has finished copying

### ISSUE THREAD

**Issue by akhilrajvc** [gorakhargosh/watchdog#586]
For large sized files, 'FileCreatedEvent' is triggered when the file first appears in the directory.
If we try to read that, we will get file corrupted exception as the file is not yet copied completely. 
The workaround what we can do is checking the file size continuously in a loop and once the size is stable, we can continue with the process:
 file_size =  0
 while file_size != os.path.getsize(event.src_path):
     file_size = os.path.getsize(event.src_path)
     time.sleep(1)
I'm not feeling this solution is a perfect one.

**Comment by rrzaripov** [comment]
@akhilrajvc same issue as in #567?
