### ISSUE TITLE
watchmedo shell-command: Exit when subcommand return a non-zero exit code

### ISSUE THREAD

**Issue by elie-g** [gorakhargosh/watchdog#599]
`watchmedo shell-command` should stop/exit when its subcommand returns a non-zero exit code.

I think the best would be to add an option to enable this behaviour cause doing so would make the change backward compatible. Otherwise, all current uses of `shell-command` where the subcommand return a non-zero exit code would break.

Example
```sh
# The following watchmedo should stop as soon as its subcommand is executed
watchmedo shell-command --command 'exit 1' .
```

**Comment by seppe-lenders-tl** [comment]
This option was added in https://github.com/gorakhargosh/watchdog/pull/946, so I believe this issue can be closed?
