### ISSUE TITLE
ImportError: cannot import name 'observer' from 'watchdog.observers' (C:\Python37\lib\site-packages\watchdog\observers\__init__.py)

### ISSUE THREAD

**Issue by CuV-Dev** [gorakhargosh/watchdog#607]
im trying to import watchdog.observers as  observer but it prints this error:

ImportError: cannot import name 'observer' from 'watchdog.observers' (C:\Python37\lib\site-packages\watchdog\observers\__init__.py)

actually I want to copy the code out of a youtube video and make it fit to me but it doesnt work.

 The link to the video is here:
https://www.youtube.com/watch?v=qbW6FRbaSl0&list=PLsbaiXk2DEWUFHPN86hRnWqsMzwlxj-2m&index=5&t=0s
(it is the second idea)

In the Video it says only import watchdog.observer as  observer but this thorows the following error:
Traceback (most recent call last):
  File "file_mover.py", line 1, in <module>
    from watchdog.observer import observer
ModuleNotFoundError: No module named 'watchdog.observer'

(Of cause I have imported Watchdog with pip before)
How can I fix this?

**Comment by CuV-Dev** [comment]
[code.zip](https://github.com/gorakhargosh/watchdog/files/4010298/code.zip)

The code

**Comment by Ajordat** [comment]
The guy from the video has made some errors in that line. He should import the class `Observer` from member `observers`.

So instead of:
`from watchdog.observer import observer`

It should be:
`from watchdog.observers import Observer`

**Comment by Ajordat** [comment]
@CuV-Dev did my last comment help you fix the issue?

**Comment by CuV-Dev** [comment]
Im very sorry that I didnt anwered before.
It fixed the error.

Thank you very much 👍 .
