### ISSUE TITLE
Does watchdog touches files and/or directories?

### ISSUE THREAD

**Issue by wolfc01** [gorakhargosh/watchdog#608]
Hello,

i want to run watchdog on a windows server as administrator in order to monitor file/directory change volume figures, this to detect excessive changes as a result of an hacker ransomware attack.

I need to be sure that watchdog does not touch files/directories in order not to disturb normal server operation. E.g. a directory removal which is hindered as it turns out to be open by watchdog? Can you elaborate on that?

Best regards
Carl.

**Comment by Ajordat** [comment]
If you are asking whether watchdog opens files/directories or updates their `created_at`/`modified_at` times, the answer is not.
