### ISSUE TITLE
[Question] why pytest test_empty_snapshot fails?

### ISSUE THREAD

**Issue by scheung38** [gorakhargosh/watchdog#614]
Just replicating your pytest but why am I getting 

test setup failed 

E    Fixture ‘p’ not found?

    Import errno 
    Import os 
    Import pickle
    Import time

    from watchdog.utils.dirsnapshot import DirectorySnapshot
    from watchdog.utils.dirsnapshot import DirectorySnapshotDiff
    from watchdog.utils import platform

    # my local copy
    from watcher.shell import mkdir, touch
    from watcher.snapshot_watcher import EmptyDirectorySnapshot

    def test_empty_snapshot(p):
    (Same content as your test_empty_snapshot)

**Comment by BoboTiG** [comment]
Please provide complete scripts, the full error, the command line used to run tests and from what source are you bass (master, pypi).

**Comment by BoboTiG** [comment]
There is a typo in an import: watchsog -> watchdog.

**Comment by scheung38** [comment]
>There is a typo in an import: watchsog -> watchdog.



@BoboTiG 

Fixed, but it was Pycharm (configured to use pytest) select and right click this example.py and :

=================================== ERRORS ====================================
____________________ ERROR at setup of test_empty_snapshot ____________________
file $HOME\watcher\tests\test_snaphot_watcher.py, line 31
  def test_empty_snapshot(p):
E       fixture 'p' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.



<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
