### ISSUE TITLE
No notifications for permission changes

### ISSUE THREAD

**Issue by kreichgauer** [gorakhargosh/watchdog#62]
Watchdog currently does not report any changes to file permissions. I will probably work on a patch for this, which I could contribute back if there is interest.

**Comment by kchaksuvej** [comment]
I changed the permission of a file but no event was raised. 
I am using PollingObserver() to monitor files on 2 machines with shared folder.  It raised event changes such as mofify or delete on file or directory. 
But it does not raise modify event when I change file permission/owner.
Any suggestions. Thanks.
