### ISSUE TITLE
Make fsevents2 the default implementation on macOS

### ISSUE THREAD

**Issue by BoboTiG** [gorakhargosh/watchdog#623]
The primary idea is to get ride of the C extension on macOS.

There is some work on `fsevents2` that is is `fsevents` using PyObjC. Current tests are disabled, and will be fixed with #546.

At term the goal is to remove `fsevents.py` and `watchdog_fsevents.c`; and rename `fsevents2.py` to `fsevents.py`. A `fsevents2.py` will be kept for compatibility and display a deprecation warning.
This will allow us to publish one wheel for every platform (#428) and fix a lot of compilation errors happening from time to time.

This issue is here to track the remaining tasks that we are not yet aware.

**Comment by SamSchott** [comment]
Uh, this would mean depending on PyObjC which is quite a heavy dependency. It's effectively outsourcing our single extension module to a dependency which covers the entire macOS API.

If you really want to get rid of `watchdog_fsevents.c`, could you be convinced to use [rubicon-objc](https://github.com/beeware/rubicon-objc) for the bridging instead? It's based on `ctypes`, it's light-weight and despite still being at v0.4.0 it is very stable. Though with the recent work which we have put into the extension module, I would not mind keeping it around either.

**Comment by BoboTiG** [comment]
Of course, given what was done lastly, there is no need to change anything. The C code is quite robust and we have more contributors knowing its internals. And we have wheels for all platforms. So my initial concerns are no longer valid.

What could be interesting, for the future, may be to port `fsevents2` to `rubicon-objc`. And at some point migrating from `fsevents` to `fsevents2`. But this is really not a priority and I am fine with the current state of `fsevents`. Of course, being able to skip C compilation is always a good point IMO.

**Comment by SamSchott** [comment]
Thanks for the update, this sounds good to me. I just stumbled upon this issue when considering to port the changes from #815 to `fsevents2`.
