### ISSUE TITLE
argh not found

### ISSUE THREAD

**Issue by bhargavrpatel** [gorakhargosh/watchdog#627]
In the latest version of watchdog (0.10.0), we have to currently, explicitly install `argh` in order our processes to start. Without `argh` explicitly installed, we see the following exception:

```python
Traceback (most recent call last):
  File "/env/bin/watchmedo", line 6, in <module>
    from watchdog.watchmedo import main
  File "/env/lib/python3.7/site-packages/watchdog/watchmedo.py", line 39, in <module>
    from argh import arg, aliases, ArghParser, expects_obj
ModuleNotFoundError: No module named 'argh'
```

**Comment by BoboTiG** [comment]
Watchmedo is now an extra. To install it and its dependencies, you have to use:
```shell
python -m pip install watchdog[watchmedo]
```
And then `argh` will be automatically installed.

**Comment by bhargavrpatel** [comment]
Sounds good, thank you!

**Comment by honglei** [comment]
argh is not automatically installed for the current version!
