### ISSUE TITLE
FreeBSD kqueue: 'module' object is not callable

### ISSUE THREAD

**Issue by evilham** [gorakhargosh/watchdog#632]
Latest version (`0.10.1`) of watchdog on FreeBSD fails with:

```
  File ".../python3.7/site-packages/watchdog/observers/kqueue.py", line 439, in custom_stat
    stat_info = stat(path)
TypeError: 'module' object is not callable
```

Downgrading to version 0.9.0 works fine, so I am guessing it has to do with changes introduced here: d092a698e0edc7e3e9075653b982a5636d592e8c

I guess #532 would be awesome to prevent this :-) good to see it's somehow on the radar!

**Comment by BoboTiG** [comment]
Arf, my bad. Thanks for the report!
Maybe could you open a PR as you are able to test it live? 🙏

**Comment by evilham** [comment]
Sure thing, will add that to my own personal queue :-D.

**Comment by evilham** [comment]
Woah, this is more complex than expected... Apparently watchdog is asking a lot of things that kqueue does not provide and... wel, everything is workarounds :-D...

I'll have to submit some patches to the tests first, this one I am not sure of:

```
@@ -226,11 +230,11 @@ def test_move_from_full():
 @pytest.mark.flaky(max_runs=5, min_passes=1, rerun_filter=rerun_filter)
 def test_separate_consecutive_moves():
     mkdir(p('dir1'))
+    touch(p('dir1', 'b'))
     touch(p('dir1', 'a'))
-    touch(p('b'))
     start_watching(p('dir1'))
     mv(p('dir1', 'a'), p('c'))
-    mv(p('b'), p('dir1', 'd'))
+    mv(p('dir1', 'b'), p('dir1', 'd'))
```

As far as the current KqueueEmitter is concerned, it looks like if we add a file from a different directory it is equivalent to that file being *created* and not renamed, as the test expects. Does this patch to the test make sense?
