### ISSUE TITLE
v0.10.1 broke Ubuntu 16.04 install via pip

### ISSUE THREAD

**Issue by mDuo13** [gorakhargosh/watchdog#635]
I manage a package ([Dactyl](https://github.com/ripple/dactyl/)) that uses watchdog as a dependency. Starting with the release of Watchdog v0.10.1, our Dockerized builds (Ubuntu 16.04) are failing on an `ImportError` for `pathtools` that ultimately comes from watchdog.

After some investigation, it appears to be that `pip3 install watchdog` no longer installs the necessary `pathtools` dependency because pip doesn't look at the `setup.cfg` file. This issue may be masked on some OSes because it's common for pathtools to be installed by default, but I was able to reproduce as follows:

1. Creating a fresh Ubuntu 16.04 install (I did it on a VM)
2. `sudo apt-get install python3-pip`
3. `pip3 install watchdog`
4. `python3`
5. At the Python prompt:

        from watchdog.observers import Observer

    The result is similar to this error:

          File "/home/username/.local/lib/python3.5/site-packages/watchdog/observers/__init__.py", line 63, in <module>
            from .inotify import InotifyObserver as Observer
          File "/home/username/.local/lib/python3.5/site-packages/watchdog/observers/inotify.py", line 83, in <module>
            from watchdog.events import (
          File "/home/username/.local/lib/python3.5/site-packages/watchdog/events.py", line 91, in <module>
            from pathtools.patterns import match_any_paths
        ImportError: No module named 'pathtools'

Manually installing `pathtools` with pip fixes the error.

I suspect the changes in commit 6baa210d605459c8d2c5ddcac146c001cdf2f24d to remove `pathtools` from `install_requires` are the cause.

**Comment by BoboTiG** [comment]
Hello,

Could you the `setuptools` version please?

**Comment by mDuo13** [comment]
Seems to happen with the system-default `setuptools` version on Ubuntu 16.04, which, I think, is 20.x?

**Comment by BoboTiG** [comment]
Could you post the output of `python -c "import setuptools; print(setuptools.__version__)"`?
I would like to check if we need to pin a minimum `setuptools` version before installing `watchdog`.

**Comment by mDuo13** [comment]
Using Python 3, yes.

I'll have to get back to you on the exact setuptools version; I don't have the VM up and running at the moment. But, again, this is whatever the default one that comes on Ubuntu 16.04.

Since Watchdog does run great when you install the dependency and Ubuntu 16.04 is going to be supported (therefore common in cloud providers) for another 14 months or so, I would urge you to change the way you specify the dependency to make it "just work" rather than pinning a minimum version.

**Comment by BoboTiG** [comment]
The thing is that if we move back to how it was done before the commit, it will break elsewhere (again, because of outdated `setuptools`).
I will need to do more tests in order to find a good fix for everyone.

**Comment by BoboTiG** [comment]
I found the right minimum version: [36.2.7](https://setuptools.readthedocs.io/en/latest/history.html#v36-2-7).

But I do not know yet how to deal with that :)
