### ISSUE TITLE
[BSD] Pass tests with KqueueEmitter

### ISSUE THREAD

**Issue by evilham** [gorakhargosh/watchdog#637]
Discovered while working on #632 which made watchdog not work on BSD systems.

By separating in two issues we can fix things progressively.

8 tests fail currently:

- [x] `tests/test_emitter.py::test_create FAILED`
- [x] `tests/test_emitter.py::test_move_to FAILED`
- [x] `tests/test_emitter.py::test_separate_consecutive_moves FAILED`
- [x] `tests/test_emitter.py::test_fast_subdirectory_creation_deletion FAILED`
- [x] `tests/test_emitter.py::test_recursive_on FAILED`
- [x] `tests/test_emitter.py::test_recursive_off FAILED`
- [x] `tests/test_emitter.py::test_renaming_top_level_directory FAILED`
- [x] `tests/test_emitter.py::test_move_nested_subdirectories FAILED`

**Comment by BoboTiG** [comment]
Could you post full errors :pray:?

**Comment by evilham** [comment]
:-D I can do better!
https://cirrus-ci.com/task/6078433516060672
