### ISSUE TITLE
Installation trips an error on non-macOS platforms because of indirect dependency on pyobjc-core

### ISSUE THREAD

**Issue by thejohnfreeman** [gorakhargosh/watchdog#643]
Installing this package on non-macOS platforms prints this error:

> An error occurred when reading setup.py or setup.cfg: 'Attribute' object has no attribute 'id'

Which is caused by [this issue](https://bitbucket.org/ronaldoussoren/pyobjc/issues/291/install-fails-on-non-macos-platforms) in pyobjc-core, which watchdog depends on through these paths:

watchdog -> pyobjc-framework-FSEvents -> pyobjc-core
watchdog -> pyobjc-framework-Cocoa -> pyobjc-core

Overall installation still succeeds, unless installing on Windows with `$ErrorActionPreference = "Stop"`.

**Comment by BoboTiG** [comment]
This will be fixed by #642. Thanks for the report :)
