### ISSUE TITLE
Watchdog thinks files with no extension are directories

### ISSUE THREAD

**Issue by axfelix** [gorakhargosh/watchdog#647]
Hi,

I've just noticed this issue seems to be present on both Mac and Windows and I haven't seen it documented anywhere -- Watchdog seems to be interpreting all files with no extension as directories, which causes a number of issues for the way we're using the project. I would assume this would be handled somewhere, so I may be missing anything, but it's nothing in our code that's causing it as far as I can tell...

**Comment by francoatmega** [comment]
Dude, can you paste your code here? I have tested if watchdogs interpret an file without extensions on my Windows 10, and there's no such error.
I'm using version 0.9.0 of watchdogs...

**Comment by axfelix** [comment]
`event.is_directory` is appearing to return `True` for regular files without extensions on Windows/Mac, it's as simple as that ... but I'll keep looking into it if this can't be reproduced.

**Comment by francoatmega** [comment]
Watchdog Version: 0.9.0
Windows 10 Version: 1903

The code that I've used...

```
import time

from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler


class EventHandler(FileSystemEventHandler):

    def on_created(self, event):
        
        if event.is_directory:

            print("Directory created " + event.src_path)

        else:

            print("File Created " + event.src_path)


def main():

    try:

        observer = Observer()
        observer.schedule(EventHandler(), path="YOUR_WATCHED_DIRECTORY", recursive=True)
        observer.start()

        print("Watching the directory ", "YOUR_WATCHED_DIRECTORY")

        while True:

            time.sleep(1)

    except Exception as e:

        print(str(e))


if __name__ == "__main__":

    main()
```

**Comment by BoboTiG** [comment]
Yup, I can confirm that extensionless files are seen as files on GNU/Linux, macOS and Windows. It may be specific to something else, out of the scope of that project.
