### ISSUE TITLE
Part of document seems to be lost

### ISSUE THREAD

**Issue by pansila** [gorakhargosh/watchdog#650]
I can't see events API descriptions on the page of [watchdog-events](https://python-watchdog.readthedocs.io/en/v0.10.2/api.html#watchdog-events)

![image](https://user-images.githubusercontent.com/5125601/74924288-2331dd80-540d-11ea-9a8f-3982bd8ef504.png)

**Comment by fastily** [comment]
here's a [link](https://watchdog.readthedocs.io/en/latest/api.html#module-watchdog.observers.api) to the most recent version of the documentation (0.9.0) which is still complete

**Comment by xrogaan** [comment]
Looking at the [build logs](https://readthedocs.org/projects/python-watchdog/builds/10405936/), these warning seems relevant:

```
Running Sphinx v1.8.5
loading translations [en]... done
making output directory...
building [mo]: targets for 0 po files that are out of date
building [readthedocs]: targets for 5 source files that are out of date
updating environment: 5 added, 0 changed, 0 removed
reading sources... [ 20%] api
reading sources... [ 40%] hacking
reading sources... [ 60%] index
reading sources... [ 80%] installation
reading sources... [100%] quickstart

WARNING: autodoc: failed to import module 'events' from module 'watchdog'; the following exception was raised:
No module named 'pathtools'
WARNING: autodoc: failed to import module 'observers.api' from module 'watchdog'; the following exception was raised:
No module named 'pathtools'
WARNING: autodoc: failed to import module 'observers' from module 'watchdog'; the following exception was raised:
No module named 'pathtools'
WARNING: autodoc: failed to import module 'observers.polling' from module 'watchdog'; the following exception was raised:
No module named 'pathtools'
/home/docs/checkouts/readthedocs.org/user_builds/python-watchdog/checkouts/v0.10.2/docs/source/installation.rst:16: WARNING: Inline substitution_reference start-string without end-string.
looking for now-outdated files... none found
```

**Comment by tritium21** [comment]
@xrogaan according to read the docs [documentation](https://docs.readthedocs.io/en/stable/guides/specifying-dependencies.html#specifying-a-requirements-file), it should be as simple as renaming `docs/dependencies.txt` to `docs/requirements.txt`.  Should.
