### ISSUE TITLE
Passing `pathlib.Path` to `Observer.schedule()` causes a trap in `Observer.start()` on MacOS

### ISSUE THREAD

**Issue by rec** [gorakhargosh/watchdog#651]
(This is not a regression of #26!  :-))

See this minimal example: https://github.com/rec/backer/blob/bpt-trap/bpt_trap.py

On MacOS, it causes a `BPT trap Compilation trace/BPT trap: 5` (something like a SEGV if you are Linux person) on Python 3.6.6, Python 3.7.0, and Python 3.8.1 exactly if `PATH` is a `pathlib.Path`.

The workaround is to cast the `Path` to a `str` before calling `Observer.schedule()`.

**Comment by BoboTiG** [comment]
Fixed in #652.
