### ISSUE TITLE
on_any_event extra arguments

### ISSUE THREAD

**Issue by Zujiry** [gorakhargosh/watchdog#660]
I would like to add arguments to the on_any_event function. As I'd like to run one watcher with different arguments, then use a different on_any_event function each time.

If I use watchdog like this, that is not possible:
```
from util import on_any_event, on_another_event

if True:
  event_handler.on_any_event = on_any_event  
else:  
  event_handler.on_any_event = on_another_event  
```

I can change the function, but I can not give an argument to self.on_any_event or self.on_another_event which is what I need.

**Comment by flgau** [comment]
did you find a way to do it? I am currently having the same problem!

**Comment by BoboTiG** [comment]
What code would you like to use exactly?
