### ISSUE TITLE
10.2 is missing code in sublibraries

### ISSUE THREAD

**Issue by schaefer01** [gorakhargosh/watchdog#662]
The instantiation of OrderedSetQueue in utils.bricks.py is missing.
A possible workaround is to take the source from 0.9, which I'll be trying right after I submit this issue.

**Comment by BoboTiG** [comment]
`OrderedSetQueue` was removed in v0.10.0 because if was no more used (cf bc8b5b9d5f9d385654e9f0d3ecee1c8e3c6134d3).
