### ISSUE TITLE
Watchdog blocks eventlet/Flask from running in debug mode.

### ISSUE THREAD

**Issue by mortoray** [gorakhargosh/watchdog#679]
Simply having watchdog installed causes flask+eventlet to hang. I've filed this issue on eventlet, but I'm not sure where it belongs.
eventlet issue: https://github.com/eventlet/eventlet/issues/634

There was  previous issue here related to eventlet:
previous watchdog issue: https://github.com/gorakhargosh/watchdog/issues/332

**Comment by merlinran** [comment]
To reproduce: https://github.com/eventlet/eventlet/issues/634#issuecomment-1000943837

I encountered this because I installed `pytest-watch` in the Docker image, which depends on `watchdog`.
