### ISSUE TITLE
watchdog on MacOS not generating event for file metadata modification (e.g. tags, Finder Comment)

### ISSUE THREAD

**Issue by tom-n-pdx** [gorakhargosh/watchdog#694]
**Problem**: Using watchdog on MacOS changes to an existing file's metadata are not being reported via an event.

I'm using a FileSystemEventHandler handler that reports all events and monitoring a file tree on my MacBook APFS hard drive. 

**How to reproduce**: Add a user tag via Finder. No event is generated. 

File creations, renames and deletions are reported ok. A Finder comment change generates a modification event for the .DS_Store file in the directory. This is a limitation of where Finder comments are stored by MacOS and I can work around it.

**Why**: I'm monitoring a filesystem to sync data between the hard drive and cloud and want to sync modifications to user tags and com.apple.metadata:KMDItem spotlight metadata.

**Workaround**: I'm open to suggestions- right now my plan is to do a full file tree walk every hour and look for changes in metadata.

**Versions**: watchdog 0.10.3 on MacOS 10.15.7 with Python 3.8.6 (homebrew install).

**Comment by BoboTiG** [comment]
Hello,

It should work but I just saw that we have no tests (https://github.com/gorakhargosh/watchdog/search?q=xattr). So maybe is there a bug there. We should start by adding a test and see if the CI fails.

**Comment by CCP-Aporia** [comment]
Thanks for the detailed report!

The changes in #716 are going to resolve this problem - the given reproduction is going to result in a `FileModifiedEvent` there. It's just a matter of re-creating them for mainline, which I hope to get done this week.

**Comment by BoboTiG** [comment]
Done with 614ccfc9342fa853a54e37c2eec4d07e9bf8fd3a.
