### ISSUE TITLE
Explicit Python 3.9 support in setup.py

### ISSUE THREAD

**Issue by benaduggan** [gorakhargosh/watchdog#696]
Hey there! 

Is there the possibility of adding python 3.9 as a supported version for this package?

**Comment by BoboTiG** [comment]
Hello,

Out of curiosity, what is preventing to install on 3.9? I just added tests for 3.9 and 3.10 the last week and everything works well.

**Comment by BoboTiG** [comment]
OK you just edited the title and I get it :)
I will do that tomorrow.

**Comment by benaduggan** [comment]
Yeah, my bad! I realized I was super unspecific at first :) thanks!
