### ISSUE TITLE
Watchdog not working on MacOS Big Sur 11.0.1

### ISSUE THREAD

**Issue by sureshjoshi** [gorakhargosh/watchdog#710]
I don't know if this problem is specifically related to Big Sur, or something else, but I have a few watchdog applications that no longer work on my system after upgrading to Big Sur. 

I'm using the example application and cannot get any file change notifications on my Mac (e.g. nothing is printed to the console). I have permissions in all the directories I'm trying to monitor as well.

```bash
sj@macos ~ % python test.py
    [Nothing happens regardless of file creation/deletion/modification]
```

However, on Debian, I'm running the same application and seeing file changes printed to the console 
```bash
sj@debian: ~$ python test.py
    [touch test.py from another tab]
    2020-12-01 12:05:38 - Modified file: ./test.py
```

My environment:
```
macOS Big Sur
11.0.1
python 3.8.6 or python 3.9.0
clang-1200.0.32.27
```

requirements.txt:
```
pathtools==0.1.2
watchdog==0.10.4
```

test.py:
```python
import sys
import time
import logging
from watchdog.observers import Observer
from watchdog.events import LoggingEventHandler

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO,
                        format='%(asctime)s - %(message)s',
                        datefmt='%Y-%m-%d %H:%M:%S')
    path = sys.argv[1] if len(sys.argv) > 1 else '.'
    event_handler = LoggingEventHandler()
    observer = Observer()
    observer.schedule(event_handler, path, recursive=True)
    observer.start()
    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        observer.stop()
    observer.join()
```

**Comment by BoboTiG** [comment]
It seems an issue on Watchdog. Stick with 0.10.3 for now, until #702 is merged.

**Comment by sureshjoshi** [comment]
Whew, thanks for the fast reply. That works!

I'll close this as it's covered in #702
