### ISSUE TITLE
watchmedo does not work on mac with 0.10.4

### ISSUE THREAD

**Issue by abessiari** [gorakhargosh/watchdog#718]
Hi.
0.10.4 does not capture events on mac. 0.10.3 works just fine. 
Did anything change that would make 0.10.4 not work on mac?
I have installed 0.10.3 and it works just fine. 
With 0.10.4 nothing happens.  Problem was produced by running watchmedo.
Thanks.
Python 3.7.9
python -m pip install -U "watchdog[watchmedo]"==0.10.3
python -m pip install -U "watchdog[watchmedo]"==0.10.4
watchmedo shell-command    --patterns="*.py;*.txt"   --recursive    --command='echo "${watch_src_path}"'    .

**Comment by BoboTiG** [comment]
Fixed by #716. I will release new versions with that important regression fix.
