### ISSUE TITLE
watchdog 1.0 lacks python-requires metadata and breaks Python 2 applications not pinning the version

### ISSUE THREAD

**Issue by ThiefMaster** [gorakhargosh/watchdog#719]
First of all, please yank the 1.0.0 release from PyPI - it's broken.

While you have the correct `python_requires` metadata in setup.py, this metadata is missing on PyPI. This may have happened because you built the package or uploaded it with outdated tooling - having the latest setuptools installed and using `twine upload` to upload the sdist (or better: the Python wheel!) usually avoids it.

What you can to do fix it:

- Yank 1.0.0 from PyPI so people no longer get it unless they explicitly ask for this version
- Release a fixed 1.0.1 version that has the correct metadata.

Tip: You can test via testpypi first in order to not pollute PyPI with a broken 1.0.1 version.

**Comment by ThiefMaster** [comment]
For example, `pip install sphinx-autobuild` pulls in the new watchdog version and thus fails on Python 2.

**Comment by BoboTiG** [comment]
Hm could you open a PR with what changes ar eeneded in order to fix the mess?
I used `setuptools==49.2.1` and a simple `python setup.py sdist upload`. Yet I know `twine` is the good move, but how does this have an impact on a release?

I am not an expert on the packaging, so any help is welcome to fix the situation ASAP :)

**Comment by ThiefMaster** [comment]
AFAIK `python setup.py sdist upload` does not include this metadata; so using twine to upload the same package should do the job. See https://stackoverflow.com/a/43851706/298479 for details.

**Comment by BoboTiG** [comment]
FTR `wheel`s are out of the table for now.

**Comment by ThiefMaster** [comment]
Ah, I didn't notice you include C code. Nevermind on the wheels then, not that important anyway :)

**Comment by BoboTiG** [comment]
I would love to release wheels, but it will be for later ;)

**Comment by BoboTiG** [comment]
OK it should be good now 🤞

**Comment by csala** [comment]
I can confirm that projects running on `python>3.5` depending on `watchdog<0.11` now pull `0.10.4` again instead of the newer 1.0.0 or 0.10.[56] versions when installed.

Thanks for the quick reaction @BoboTiG !
