### ISSUE TITLE
0.10.5 release breaks all python>3.5 projects that depended on watchdog (without prev. warning)

### ISSUE THREAD

**Issue by csala** [gorakhargosh/watchdog#720]
Something similar to what is reported in #719 happens with 0.10.5.

All the projects which I work on that use watchdog carefully depend on `'watchdog>=X.Y.Z,<0.11',` to ensure that newer versions that break the API are not included, as only versions up to 0.10.X had been tested.

After the latest release, all the projects using `python>3.5` fall apart due to the lack of python support.

So, just like #719 suggested, I think the PyPI release process should be adapted to avoid all these problems.

My suggestion would be:
1. Yank (or actually delete) 0.10.5 so dependencies are not broken on all the dependent projects.
2. Either:
    a. remove the python version constraints on 0.10.X and release a new 0.10.6 version that does not break everything else.
    b. release the maintenance version as 0.11.0 and keep that 0.11.x as the backwards compatible fork.

**Comment by BoboTiG** [comment]
Let's talk about that in #719 :)
