### ISSUE TITLE
Renamed events crash the emitter thread on macOS

### ISSUE THREAD

**Issue by SamSchott** [gorakhargosh/watchdog#721]
Any renamed events crash the emitter thread on macOS with the following exception:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/watchdog/observers/fsevents.py", line 97, in queue_events
    and events[i + 1].event_id == event.event_id + 1):
AttributeError: '_watchdog_fsevents.NativeEvent' object has no attribute 'event_id'
```

The issue, similar to #702, is that the `event_id` attribute is not defined on the `_watchdog_fsevents.NativeEvent` class. 

I understand that the tests on macOS are currently all skipped and I *will* submit a PR to fix them. However, until this happens, could you at least test the releases manually by just creating / modifying / renaming a couple of files and seeing if events are emitted? If this is not possible, for instance because you don't have access to the platforms, could you hold off on the next release until the tests are working?

**Comment by SamSchott** [comment]
Another issue seems to be that those crashes are "silent" (tracebacks don't get printed to the console) which makes them a lot more difficult to notice and report back to you.

**Comment by BoboTiG** [comment]
I will hold off for now :)

**Comment by SamSchott** [comment]
Thanks! And I promise I will contribute to the fixes. It's just difficult for me to keep up with your speed :)

**Comment by HEmile** [comment]
When will this fix be on Pypi?
