### ISSUE TITLE
Renamed events are not properly combined on macOS 11

### ISSUE THREAD

**Issue by SamSchott** [gorakhargosh/watchdog#723]
On macOS 11 and possibly previous releases, renamed events are not properly combined to a single event but are reported as separate deleted and created events instead.

The FSEventStream on macOS always reports two renamed events: one at the old path and one at the new path. Watchdog tries to combine them intelligently and relies on an undocumented observation that the event IDs of those two events will only differ by one:

https://github.com/gorakhargosh/watchdog/blob/d0bb7b8b66b9a2bb1493b69af094ed4d0ea692df/src/watchdog/observers/fsevents.py#L88-L96

However, macOS 11, the two events will have **equal** event IDs. This may be the result of changes to APFS and atomic file moves.

**Comment by SamSchott** [comment]
Those event IDs which Python receives are definitely strange. They are not monotonically increasing and often repeat themselves. Those surely cannot be the event IDs as documented in https://developer.apple.com/documentation/coreservices/fseventstreameventid?language=objc.

@CCP-Aporia, do you have any idea what may be going on here?

**Comment by SamSchott** [comment]
Ok, I found the issue: you have been passing event flags instead of IDs:

https://github.com/gorakhargosh/watchdog/blob/d0bb7b8b66b9a2bb1493b69af094ed4d0ea692df/src/watchdog_fsevents.c#L302-L304

**Comment by HEmile** [comment]
I'm having trouble handling `EVENT_TYPE_MODIFIED` on my macOS 10.15.6. The event doesn't fire, and afterward renaming a file, no other events fire either. Is this related?

**Comment by SamSchott** [comment]
No, that is issue #721 which has already been fixed in the master branch.
