### ISSUE TITLE
Delete broken 1.0.0 release from pypi?

### ISSUE THREAD

**Issue by llamasoft** [gorakhargosh/watchdog#730]
We had a nasty surprise today with the botched [1.0.0 pypi release](https://pypi.org/project/watchdog/1.0.0/).  Unfortunately, even after the 1.0.1 version was released with the "Requires: Python >=3.6" metadata, the yanked 1.0.0 package is still causing a major headache.  Currently, pip has [an open issue](https://github.com/pypa/pip/pull/9226) involving yanked packages not being ignored.  If you run `pip install --verbose watchdog` using the latest version of pip on Python 2.7, it'll still try (and fail) to install the 1.0.0 package even though it's been yanked.

We've fixed things on our end by pinning watchdog's version, but I wanted to give you a heads up in case there was anything you could do on your end as well.

**Comment by BoboTiG** [comment]
HM trying locally will install 0.10.6 with Python 2.7, not 1.0.1. But I can remove the release yes.
