### ISSUE TITLE
Publish wheels for macOS ARM

### ISSUE THREAD

**Issue by BoboTiG** [gorakhargosh/watchdog#740]
Waiting on https://github.com/joerick/cibuildwheel/pull/484 before giving a try.
That will ease the support of new Apple Silicon machines.

**Comment by SamSchott** [comment]
Oh, that would be great :) I'm not sure about the state of Python packaging but a universal wheel might also be good.

Watchdog is currently my only Python dependency with an extension module and therefore keeping me from shipping a fully universal app bundle.

**Comment by di** [comment]
@SamSchott Python packaging can definitely handle a universal wheel 😅 This project, however, can't ship a universal wheel because it requires platform-specific built distributions for macOS.

**Comment by di** [comment]
@BoboTiG Looks like this was added in https://pypi.org/project/cibuildwheel/1.9.0/. The pipeline here just uses the latest version, so the next release should include the ability to build for Apple Silicon via cross-compiling: https://cibuildwheel.readthedocs.io/en/stable/faq/#apple-silicon

**Comment by di** [comment]
Ah, got it! Yes it shouldn't be a problem to publish a `universal2` wheel here in addition to the architecture-specific ones.

**Comment by BoboTiG** [comment]
macOS arm64 and universal2 wheels are online :)

**Comment by SamSchott** [comment]
Nice! Greatly appreciated :)
