### ISSUE TITLE
FileDeletedEvent not appearing in unit tests since 0.10.3 (MacOS)

### ISSUE THREAD

**Issue by sureshjoshi** [gorakhargosh/watchdog#749]
I've run into a strange problem and I think it might be a bug, but I'm not sure where/why exactly yet. 

I'll create a full reproduction repo (hopefully tonight) when I get a chance, but here's the short form without much code. I have a unit test testing a file event monitor using `tempfile`. This test worked until 0.10.3, but now no longer works (I've tried each version on PyPi > 0.10.3 (except 0.10.4 as per #710)

Events received for each operation shown in comments.

I should note though, that this project works correctly at runtime and I get FileDeletedEvents on all versions of `watchdog`...

Environment:

```bash
macOS Big Sur
11.1
python 3.9.1
clang-1200.0.32.28
```

**v0.10.3**
```python
with tempfile.NamedTemporaryFile(prefix=PREFIX, suffix=EXTENSION, dir=dir) as file:
    path = Path(file.name)
    # Emits: FileCreatedEvent
    path.touch()
    # Emits: FileModifiedEvent
# Emits: FileDeletedEvent
assert blahblahblah
```

**v1.0.0**, **v1.0.1**, **v1.0.2**
```python
with tempfile.NamedTemporaryFile(prefix=PREFIX, suffix=EXTENSION, dir=dir) as file:
    path = Path(file.name)
    # Emits: FileCreatedEvent
    path.touch()
    # Emits: FileModifiedEvent
# Emits: FileModifiedEvent ???
assert blahblahblah
```

I've confirmed that the temp file is correctly deleted after the context manager exits, and all code/dependencies/environments remained the same between tests other than Watchdog.

**Comment by BoboTiG** [comment]
Coul you try again with the current master branch?

**Comment by sureshjoshi** [comment]
No dice, same problem

**Comment by sureshjoshi** [comment]
Okay, no repo needed - this test is enough. Added sleeps to make sure I wasn't being hit with timing issues. 

As mentioned earlier, **0.10.3** passes this test [`FileCreated`, `FileModified`, `FileDeleted`], **1.0.2** fails it [`FileCreated`, `FileModified`, `FileModified`]

What's interesting is that **master** also fails it, but a different fail (returns 4 events):
[`FileCreated`, `FileCreated`, `FileModified`, `FileDeleted`]

This is weird, because when using **master** in my production code directly, I still wasn't getting the `FileDeleted` in my equivalent unit test - but on this reproduction file, I am getting that deletion event.

```python
from pathlib import Path
import tempfile
import time

from watchdog.observers import Observer 
from watchdog.events import FileCreatedEvent, FileModifiedEvent, FileDeletedEvent

events = []

class EventHandler:
    def dispatch(self, event):
        if event.is_directory:
            return
        global events
        events.append(event)
        print(f"Dispatching event... {event}")

def issue749(path: Path):
    watchdog = Observer()
    watchdog.schedule(EventHandler(), path, recursive=True)
    watchdog.start()

def test_issue749(tmp_path):
    issue749(tmp_path)
    time.sleep(1)
    with tempfile.NamedTemporaryFile(prefix="749-", dir=tmp_path) as file:
        path = Path(file.name)
        time.sleep(1)
        path.touch()
        time.sleep(1)
    time.sleep(1)

    assert len(events) == 3
    assert isinstance(events[0], FileCreatedEvent)
    assert isinstance(events[1], FileModifiedEvent)
    assert isinstance(events[2], FileDeletedEvent)
```

Including directories, here is what **0.10.3** produces:

```bash
Dispatching event... <FileCreatedEvent: src_path='/private/var/folders/18/q1r7phps28nc9rx5j_0t3jmm0000gp/T/pytest-of-sj/pytest-29/test_issue7490/749-d68x7jxm'>
Dispatching event... <DirModifiedEvent: src_path='/private/var/folders/18/q1r7phps28nc9rx5j_0t3jmm0000gp/T/pytest-of-sj/pytest-29/test_issue7490'>
Dispatching event... <FileModifiedEvent: src_path='/private/var/folders/18/q1r7phps28nc9rx5j_0t3jmm0000gp/T/pytest-of-sj/pytest-29/test_issue7490/749-d68x7jxm'>
Dispatching event... <FileDeletedEvent: src_path='/private/var/folders/18/q1r7phps28nc9rx5j_0t3jmm0000gp/T/pytest-of-sj/pytest-29/test_issue7490/749-d68x7jxm'>
Dispatching event... <DirModifiedEvent: src_path='/private/var/folders/18/q1r7phps28nc9rx5j_0t3jmm0000gp/T/pytest-of-sj/pytest-29/test_issue7490'>
```

Including directories, here is what **1.0.2** produces:
```bash
Dispatching event... <DirCreatedEvent: event_type=created, src_path='/private/var/folders/18/q1r7phps28nc9rx5j_0t3jmm0000gp/T/pytest-of-sj/pytest-28/test_issue7490', is_directory=True>
Dispatching event... <DirModifiedEvent: event_type=modified, src_path='/private/var/folders/18/q1r7phps28nc9rx5j_0t3jmm0000gp/T/pytest-of-sj/pytest-28', is_directory=True>
Dispatching event... <FileCreatedEvent: event_type=created, src_path='/private/var/folders/18/q1r7phps28nc9rx5j_0t3jmm0000gp/T/pytest-of-sj/pytest-28/test_issue7490/749-58jdkdt8', is_directory=False>
Dispatching event... <DirModifiedEvent: event_type=modified, src_path='/private/var/folders/18/q1r7phps28nc9rx5j_0t3jmm0000gp/T/pytest-of-sj/pytest-28/test_issue7490', is_directory=True>
Dispatching event... <FileModifiedEvent: event_type=modified, src_path='/private/var/folders/18/q1r7phps28nc9rx5j_0t3jmm0000gp/T/pytest-of-sj/pytest-28/test_issue7490/749-58jdkdt8', is_directory=False>
Dispatching event... <FileModifiedEvent: event_type=modified, src_path='/private/var/folders/18/q1r7phps28nc9rx5j_0t3jmm0000gp/T/pytest-of-sj/pytest-28/test_issue7490/749-58jdkdt8', is_directory=False>
```

Including directories, here is what **master** produces:

```bash
Dispatching event... <DirCreatedEvent: event_type=created, src_path='/private/var/folders/18/q1r7phps28nc9rx5j_0t3jmm0000gp/T/pytest-of-sj/pytest-27/test_issue7490', is_directory=True>
Dispatching event... <DirModifiedEvent: event_type=modified, src_path='/private/var/folders/18/q1r7phps28nc9rx5j_0t3jmm0000gp/T/pytest-of-sj/pytest-27', is_directory=True>
Dispatching event... <FileCreatedEvent: event_type=created, src_path='/private/var/folders/18/q1r7phps28nc9rx5j_0t3jmm0000gp/T/pytest-of-sj/pytest-27/test_issue7490/749-pqcxgywd', is_directory=False>
Dispatching event... <DirModifiedEvent: event_type=modified, src_path='/private/var/folders/18/q1r7phps28nc9rx5j_0t3jmm0000gp/T/pytest-of-sj/pytest-27/test_issue7490', is_directory=True>
Dispatching event... <FileCreatedEvent: event_type=created, src_path='/private/var/folders/18/q1r7phps28nc9rx5j_0t3jmm0000gp/T/pytest-of-sj/pytest-27/test_issue7490/749-pqcxgywd', is_directory=False>
Dispatching event... <DirModifiedEvent: event_type=modified, src_path='/private/var/folders/18/q1r7phps28nc9rx5j_0t3jmm0000gp/T/pytest-of-sj/pytest-27/test_issue7490', is_directory=True>
Dispatching event... <FileModifiedEvent: event_type=modified, src_path='/private/var/folders/18/q1r7phps28nc9rx5j_0t3jmm0000gp/T/pytest-of-sj/pytest-27/test_issue7490/749-pqcxgywd', is_directory=False>
Dispatching event... <FileDeletedEvent: event_type=deleted, src_path='/private/var/folders/18/q1r7phps28nc9rx5j_0t3jmm0000gp/T/pytest-of-sj/pytest-27/test_issue7490/749-pqcxgywd', is_directory=False>
Dispatching event... <DirModifiedEvent: event_type=modified, src_path='/private/var/folders/18/q1r7phps28nc9rx5j_0t3jmm0000gp/T/pytest-of-sj/pytest-27/test_issue7490', is_directory=True>
```

The trend seems to be more events :)

**Comment by BoboTiG** [comment]
@CCP-Aporia and @SamSchott WDYT of the new behavior?

**Comment by CCP-Aporia** [comment]
Wow, thanks for providing such a detailed test case and log!

The behaviour in `1.0.2` is clearly wrong and fallout from not handling coalesced events from `fseventsd`well. The behaviour in `master` looks a lot better, let me try to explain what happens here:

1. The additional `DirCreatedEvent` at the beginning is because we're now also watching the watched folder itself, e.g. the root notifications that we missed out before and would thus cause a bug when moving the watched folder.
2. The additional `FileCreatedEvent` / `DirModifiedEvent` pair happens due to the file creation operation in `NamedTemporaryFile` being coalesced with the `touch` operation by `fseventsd`.

Without those 4 extra events the behaviour looks like it is in `0.10.3` if I'm not mistaken. We probably need to expand the changelog entry and documentation for the `FSEventsEmitter` that additional events may happen if file operations happen in quick succession due to how `fseventsd` works. Unfortunately this is a bit of a leaky abstraction.

**Comment by sureshjoshi** [comment]
Thanks for the quick reply!

Also, thanks for the feedback on how it's supposed to work now. It's unfortunate that there is a leaky abstraction, because the latest master behaviour is very unintuitive, and actually looks/feels like a bug.

What I would have assumed without reading any documentation and ignoring the current behaviour in each version, would be something like:

`DirCreated` -> Watching the newly created root directory
`FileCreated` -> Tempfile was created in that directory
`DirModified` -> Tempfile was touched
`FileModified` -> Tempfile was touched
`DirModified` -> Tempfile was deleted
`FileDeleted` -> Tempfile was deleted

So, the two buggy-ish feeling behaviours in master would be: FileCreated emitted twice, and dir + file event pairs not happening in same order each time (e.g dir then file, or file then dir).

> that additional events may happen if file operations happen in quick succession due to how fseventsd works

Could you also document a rough idea of what "quick succession" implies? I added a 1 second sleep between events to avoid some filesystem quirks, but I guess that's not long enough? In my production application, there is naturally seconds or minutes between file creation, so none of these problems affect me - but I would like to future proof my code.

Also, I just ran the same test on **1.0.2** on Debian 10 (Python 3.9.1), which is my production environment, and the results were different again.

**Comment by CCP-Aporia** [comment]
Unfortunately there is no official documentation on the interval at which `fseventsd` coalesces multiple changes into a single event. [A very old Ars Technica article](https://arstechnica.com/gadgets/2007/10/mac-os-x-10-5/7/) mentions "30 seconds" so maybe "quick succession" is a bit of a euphemism...

That you see different results on other operating systems and other emitters is an unfortunate reality as far as I understand it - for example, the emitter tests have special casing of event sequences for different operating systems. Uniform behaviour would certainly be better, but might not be trivially achievable.

**Comment by sureshjoshi** [comment]
Thanks for the feedback. 

I can write some app-level code to handle this behaviour in my specific use case. Also, as the abstraction is kinda leaky, seeing different behaviour on different operating systems can be expected and I agree, would be a mild nightmare to implement and maintain.

It looks like my original report of `FileDeleted` not appearing is handled in master though, so should I close this ticket? Or wait until the next release?

**Comment by BoboTiG** [comment]
[2.0.0](https://github.com/gorakhargosh/watchdog/releases/tag/v2.0.0) is out!
