### ISSUE TITLE
File pattern **/*.py do not match main.py

### ISSUE THREAD

**Issue by benpigchu** [gorakhargosh/watchdog#753]
When I run the following command:
```
watchmedo auto-restart -d . -p "**/*.py" -R python main.py
```
I expect that editing the main.py will trigger an auto-restart, however it didn't.

I read the source code and found that it use the [match function from pathlib](https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.match), however it is not clear in the documentation if `**` is supported in the pattern.

After a simple test I found that it partially support `**`, but with some surprising behavior.
```python
>>> PurePath('a.py').match('**/*.py')
False #!!!
>>> PurePath('/a.py').match('**/*.py')
True
>>> PurePath('a/a.py').match('**/*.py')
True
>>> PurePath('a/a/a.py').match('**/*.py')
True
>>> PurePath('a/a/a/a.py').match('**/*.py')
True
>>>
```

This seems to be a Python bug (see [this message](https://bugs.python.org/msg382535) under [this issue](https://bugs.python.org/issue29249)), but maybe we can have some workaround to bypass this issue.

As a workaround, I am using `"*.py;**/*.py"` patterns instead of `"**/*.py"` now.

**Comment by adamlwgriffiths** [comment]
`*.py` or equivalent works when using "watchmedo".
It doesn't work when using the [example code](https://pythonhosted.org/watchdog/quickstart.html#a-simple-example).

Specifically, if you have the following files:
* test.py (`while True: time.sleep(1)`)
* example.py (with the example code)
* some_dir/test.js

`watchmedo auto-restart -d . -p "*.js" -R python test.py`
This detects changes to test.js.

However, running `python example.py *.js`, changes to test.js are not detected.

**Comment by BoboTiG** [comment]
Let's move to #798 for the next.
