### ISSUE TITLE
How about cutting a new release?

### ISSUE THREAD

**Issue by SamSchott** [gorakhargosh/watchdog#761]
I know that I was previously a bit critical about too fast releases. But seeing that the fundamental issues with the fsevents emitter are fixed now, what do you think about cutting a new release? Or are there any particular problems you'd like to see solved before version 1.0.3?

**Comment by BoboTiG** [comment]
No problem :)
I'll release 2.0.0 tomorrow (French time). The major number bump is due to the lost of macOS < 10.12.

**Comment by BoboTiG** [comment]
[2.0.0](https://github.com/gorakhargosh/watchdog/releases/tag/v2.0.0) is out!

**Comment by SamSchott** [comment]
Nice, thanks!
