### ISSUE TITLE
[fsevents] What appears to be debugging information logged with `info` level

### ISSUE THREAD

**Issue by globau** [gorakhargosh/watchdog#773]
#734 introduced the following:

https://github.com/gorakhargosh/watchdog/blob/331fd7c2c819663be39bc146e78ce67553f265fa/src/watchdog/observers/fsevents.py#L94-L96

As this appears to be debugging output, it should use `logger.debug` not `logger.info`.

**Comment by BoboTiG** [comment]
Could you open a PR please?
