### ISSUE TITLE
Force polling observer for tricks?

### ISSUE THREAD

**Issue by aodj** [gorakhargosh/watchdog#780]
Hello, does anyone know if it's possible to force the use of the `PollingObserver` in tricks? I would like to setup a `tricks.yaml` but the share I'm using in Kubernetes doesn't propagate inotify events properly, forcing me to use the polling observer.

I can do this for single events using the `--debug-force-polling` but that doesn't appear to be supported when using the `tricks.yaml`.

**Comment by BoboTiG** [comment]
Fixed with 7728a4525402dd01b21a22a6da1bc0010719b454.
