### ISSUE TITLE
Problem in SunOS/Solaris

### ISSUE THREAD

**Issue by xabi12** [gorakhargosh/watchdog#784]
Hi, I am using SunOS/Solaris (Oracle Solaris 11.4 SPARC/ SunOS 5.11) and unfortunately the library does not work ? The problem lies with ld.so. Can someone help me ?

```python
/python_venv/lib/python3.9/site-packages/watchdog-2.0.3-py3.9.egg/watchdog/observers/inotify_c.py", line 65, in <module>
    raise UnsupportedLibc("Unsupported libc version found: %s" % libc._name)
watchdog.utils.UnsupportedLibc: Unsupported libc version found: libc.so.1
```
```shell
$ find / -name libc.so.1 2>&1 | grep -v "Permission denied"
/usr/lib/sparcv9/libc.so.1
/usr/lib/libc.so.1
/lib/libc.so.1
/lib/sparcv9/libc.so.1

$ echo $LD_LIBRARY_PATH
://usr/lib/sparcv9/
```

**Comment by BoboTiG** [comment]
What is the result of that Python code?
```python
import ctypes

libc = ctypes.CDLL(None)
assert hasattr(libc, 'inotify_init')
```

**Comment by xabi12** [comment]
test2.py
Traceback (most recent call last):
  File "/export/home/watchdog_t/test2.py", line 4, in <module>
    assert hasattr(libc, 'inotify_init')
AssertionError
(python_venv)

**Comment by BoboTiG** [comment]
And what about running the same script like:
```shell
LD_LIBRARY_PATH=/usr/lib/sparcv9 python test2.py
```
?

**Comment by xabi12** [comment]
LD_LIBRARY_PATH=/usr/lib/sparcv9 python test2.py
LD_LIBRARY_PATH=/usr/lib python test2.py
LD_LIBRARY_PATH=/lib/sparcv9 python test2.py
LD_LIBRARY_PATH=/lib python test2.py

identical error message

**Comment by BoboTiG** [comment]
Oh sorry, I just tilted that Solaris is not yet implemented. I close this issue for #10 where you can follow the eventual progression.

**Comment by xabi12** [comment]
I thought something had moved on since 2010 :)
thanks for your help
