### ISSUE TITLE
Request: an on_closed-event

### ISSUE THREAD

**Issue by UnitedMarsupials** [gorakhargosh/watchdog#791]
I understand, that some event back-ends will not be able to provide this. But those -- like `inotify` -- that can, _should_.

My program needs to monitor a large number of files for growth, but, it so happens, that -- once such a file is closed (by the application writing to it), it will never be reopened again. Which means, I could stop watching it -- reducing the load on the system.

I'd love to be able to implement this using simply an `on_close` method -- I already have the `on_deleted` one...

**Comment by BoboTiG** [comment]
It is already done with #747 ;)

**Comment by BoboTiG** [comment]
Not yet. There is a good amount of work on the subject...
