### ISSUE TITLE
Seems broken on PyPy + Windows

### ISSUE THREAD

**Issue by oprypin** [gorakhargosh/watchdog#792]
I tried to apply "watchdog" to a project here: https://github.com/mkdocs/mkdocs/pull/2385

It works fine for everything, but on Windows PyPy3.6 the watches seem to silently produce no events.

Then I saw that https://github.com/gorakhargosh/watchdog/commit/dbc5689c1b597e6b6eaf0fbfbab4f856f579edf6 kinda just removed PyPy from CI.

I launched a CI run with PyPy added back: https://github.com/oprypin/watchdog/actions/runs/825872726
And indeed, watchdog's own tests are failing just a well.

So, is PyPy supposed to be supported still?

**Comment by oprypin** [comment]
I don't think it's right to assume that the tests fail because they are slow. I would assume the opposite - that they are slow only because they fail with a timeout. Some tests succeed only occasionally, and when they do, they're very fast then.

**Comment by oprypin** [comment]
Forgot CI link with passing tests: https://github.com/oprypin/watchdog/runs/2549604801?check_suite_focus=true

**Comment by BoboTiG** [comment]
I stand corrected, thanks for the investigation.
Do you mind opening a PR with that fix + mine + changelog entry?

**Comment by oprypin** [comment]
Uh sorry, what I have there is not a fix. The library really has a flaw, and adding a sleep into tests would only conceal it.

**Comment by BoboTiG** [comment]
The test fix may still be revelant for later though.
Let's see if anyone has an idea how to deal with that then.

**Comment by BoboTiG** [comment]
Done with 50af6ebc7b0533d7826752a13a6008704856702a.

**Comment by oprypin** [comment]
I found that this delay is a general issue on Windows. There is always a chance that events right after `start` will be missed, just that on PyPy that chance was very high.


I am presenting 2 runs of unittests (not of *watchdog* but of some other project using *watchdog*)
where the test suite is repeated 50 times per platform

The only difference between the two runs is the added sleeps:
https://github.com/oprypin/mkdocs/compare/ac66e7de5ced56007b346ff18b7709746780970b..c6923117a39cb2a5ed335e709960997866c1300d
-- The sleeps are analogous to those that I added to *watchdog*.

Without sleeps, on Windows it fails 13 out of 200 times (total over all versions): https://github.com/oprypin/mkdocs/actions/runs/857713565
With sleeps passes everything: https://github.com/oprypin/mkdocs/actions/runs/857723657
(Of course, now PyPy succeeds consistently in either case :D)
