### ISSUE TITLE
Observation does not work on mac anymore:

### ISSUE THREAD

**Issue by idefixcert** [gorakhargosh/watchdog#797]
Hi and thanx for this library.

I have an Observer that listens on *.json files:
```python
        event_handler = PatternMatchingEventHandler(patterns=["*.json"],
                                                    ignore_patterns=[],
                                                    ignore_directories=True)
        event_handler.on_any_event = self.load_daemon_map
        self.observer = Observer()
        self.observer.schedule(event_handler, self.pid_folder)
        self.observer.start()
```
And I create a simple test, that just creates a new File:
with watchdog 2.0.3 I get:
```
<FileCreatedEvent: event_type=created, src_path='/Users/chris/development/rtbrick/projects/cli2/mgmtd/tests/testdata/pidfolder/confd.json', is_directory=False>
<FileModifiedEvent: event_type=modified, src_path='/Users/chris/development/rtbrick/projects/cli2/mgmtd/tests/testdata/pidfolder/confd.json', is_directory=False>
```
But with watchdog 2.1.1 no event is fired anymore.

Do I miss anything or is this a bug?

This issue does not arrive at ubuntu/bionic:
```
load: <FileCreatedEvent: event_type=created, src_path='./tests/testdata/pidfolder/confd.json', is_directory=False>
load: <FileModifiedEvent: event_type=modified, src_path='./tests/testdata/pidfolder/confd.json', is_directory=False>
load: <FileClosedEvent: event_type=closed, src_path='./tests/testdata/pidfolder/confd.json', is_directory=False>
```

**Comment by oprypin** [comment]
I can confirm this via GitHub Actions.

Run where only Mac doesn't produce any events:
https://github.com/oprypin/watchdog/runs/2567960137?check_suite_focus=true

Source code:
https://github.com/oprypin/watchdog/compare/60fc1b6ecdab538751ac0f3000448230660e4f6f

**Comment by oprypin** [comment]
And a bisect:
https://github.com/oprypin/watchdog/runs/2568398200?check_suite_focus=true

> **1c67997dc3e24873f5647e8bd42dec5a15f671bd is the first bad commit**

Source code:
https://github.com/oprypin/watchdog/commit/1e9e2a409b845b1e44e6de8bf5b7bdc487bd5541

**Comment by CCP-Aporia** [comment]
Hey, thanks for reporting this problem! Unfortunately I cannot seem to reproduce the issue. Could you take a look at the test I've added in my fork, and see if there's anything missing in it?
