### ISSUE TITLE
API docs not building due to pathtools dep

### ISSUE THREAD

**Issue by waveform80** [gorakhargosh/watchdog#801]
The API documentation for watchdog on ReadTheDocs is currently largely empty: https://python-watchdog.readthedocs.io/en/v0.10.3/api.html

This is because during the build, the autodoc extension fails to import various modules which depend on the "pathtools" module which hasn't been installed in the docs build environment. This can be seen in the builds log at https://readthedocs.org/projects/python-watchdog/builds/11494634/ (expand the eighth item from the top to see the errors).

I do note that the latest version of the docs at https://python-watchdog.readthedocs.io/en/latest/api.html doesn't have this issue because #704 removed the dependency on pathtools. Unfortunately the "latest" link is neither default (which is reasonable) nor visible in the selectable versions (which probably isn't such a great idea).

I'd recommend either that the current default docs served by readthedocs are updated to build the API docs successfully (this can be achieved quite easily by with the [autodoc_mock_imports](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html?highlight=mock#confval-autodoc_mock_imports) option in `docs/source/conf.py`) or that the "latest" link is made visible in the selectable options.

Finally a quick note that this issue is related to #666 (which mentions this issue in a comment), and #731 (which also mentions this issue in a comment).

**Comment by BoboTiG** [comment]
Hello @waveform80,

I am improving the documentation situation:
- https://python-watchdog.readthedocs.io/en/v0.10.7/api.html is available, and it is correctly printed.
- The `stable` version will be displayed by default.
