### ISSUE TITLE
windows tracebacks caused by use of os.setsid & os.killpg

### ISSUE THREAD

**Issue by replabrobin** [gorakhargosh/watchdog#809]
The watchmedo command attempts to make use of these attributes on windows. The python docs say these are unix only. Whether that includes OSX I cannot say.

**Comment by replabrobin** [comment]
I did a few quick hacks in tricks/__init__.py to make this work (at least for python3.9 & windows 10 amd64). 

1) leave off the prexec_fn=os.setsid in the Popen. 

2) turn os.killpg(os.getpgid(self.process.pid), self.stop_signal) into os.kill(self.process_id,self.stop_signal)

that seemed to make things work and a simple watchmedo auto-restart did then work and restart on file events as expected.

**Comment by BoboTiG** [comment]
Could you open a PR?

**Comment by replabrobin** [comment]
Done

**Comment by BoboTiG** [comment]
Thanks a lot for the patch :muscle:
