### ISSUE TITLE
watchmedo not working on M1 Mac

### ISSUE THREAD

**Issue by diogohudson** [gorakhargosh/watchdog#838]
Hey Guys,

We have two mac Big Sur, one intel and the other M1. watchmedo is not working when called from the M1.

`test_app| Inotify._raise_error()
test_app | File "/usr/local/lib/python3.8/dist-packages/watchdog/observers/inotify_c.py", line 405, in _raise_error
test_app | raise OSError(err, os.strerror(err))
**test_app | OSError: [Errno 38] Function not implemented**
test_app_valid exited with code 1
test_app exited with code 1`

watchmedo is being called inside a docker image. 

Our compose.yml command:
`command: watchmedo auto-restart -d test_app/test_app_valid/ -p '*.py' -- python3 -m debugpy --listen 0.0.0.0:20000 -m test_app. test_app_valid
`

**Comment by BoboTiG** [comment]
It seems the docker image does not know `inotify` stuff. What is the base OS of the docker image?

**Comment by aantn** [comment]
I'm having a similar issue with the watchdog library (not watchmedo):

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/app/robusta/utils/directory_watcher.py", line 47, in watch
    observer.start()
  File "/usr/local/lib/python3.8/site-packages/watchdog/observers/api.py", line 256, in start
    emitter.start()
  File "/usr/local/lib/python3.8/site-packages/watchdog/utils/__init__.py", line 93, in start
    self.on_thread_start()
  File "/usr/local/lib/python3.8/site-packages/watchdog/observers/inotify.py", line 118, in on_thread_start
    self._inotify = InotifyBuffer(path, self.watch.is_recursive)
  File "/usr/local/lib/python3.8/site-packages/watchdog/observers/inotify_buffer.py", line 35, in __init__
    self._inotify = Inotify(path, recursive)
  File "/usr/local/lib/python3.8/site-packages/watchdog/observers/inotify_c.py", line 155, in __init__
    Inotify._raise_error()
  File "/usr/local/lib/python3.8/site-packages/watchdog/observers/inotify_c.py", line 405, in _raise_error
    raise OSError(err, os.strerror(err))
OSError: [Errno 38] Function not implemented
```

The base image is python:3.9-slim.

**Comment by BoboTiG** [comment]
@aantn, could you provide minimal repoduction  steps?

**Comment by BoboTiG** [comment]
Even without being able to reproduce, can you tell me what to do to try reproducing?

**Comment by chrisdail** [comment]
If you have the flexibility of using an `arm64` based container, this is also another solution to this problem. The docker issue is with `inotify` under the emulation mode only. If you have the option to use an arm based container, `watchdog` should work normally.

**Comment by boomshadow** [comment]
> We've spent a lot of time working on this and the problem is that emulation on M1 does not support `inotify` .. This is documented here:
> 
> https://docs.docker.com/desktop/mac/apple-silicon/
> 
> > In addition, filesystem change notification APIs (inotify) do not work under qemu emulation. Even when the containers do run correctly under emulation, they will be slower and use more memory than the native equivalent.
> 
> We've had to start removing `watchdog` from our python setups to support our M1 devs. Fortunately, some libraries (like `flask`) have alternative options to auto-reloading outside of using `inotify` but not all do.

Because the problem is entirely related to `qemu` if you switch from Docker desktop to [OrbStack](https://github.com/orbstack/orbstack), the problem goes away! You can have `watchmedo` on Apple Silicon once again!

**Comment by BoboTiG** [comment]
Thanks a lot for the information @boomshadow 🍾
