### ISSUE TITLE
Not working on HPC or parallel filesystem

### ISSUE THREAD

**Issue by AhmadMaroofKarimi** [gorakhargosh/watchdog#860]
Hi, I am trying to use `watchdog` to see the newly created files in a directory on a parallel file system (GPFS) in an HPC environment. The code does not detect the file created or modified, however when I run the same sample code on my laptop, the code is able to track the updates. The sample code is taken from the Github page and is as follows:

```
import sys
import time
import logging
import glob
from watchdog.observers import Observer
from watchdog.events import LoggingEventHandler

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO,
                        format='%(asctime)s - %(message)s',
                        datefmt='%Y-%m-%d %H:%M:%S')
    path = sys.argv[1] if len(sys.argv) > 1 else '.'
    path = '.'
    files_count = glob.glob(path) #test whehter code has access to the list of files
    print("length: ",len(files_count))
    event_handler = LoggingEventHandler()
    observer = Observer()
    observer.schedule(event_handler, path, recursive=True)
    observer.start()
    try:
        while True:
            time.sleep(1)
    finally:
        observer.stop()
        observer.join()
```
Just to be sure, and to test whether python code can access the files, I have used `glob` package and it is giving the expected result. 

My question is, am I missing something or the `watchdog` package does not work on a parallel filesystem?

Thank you

**Comment by AhmadMaroofKarimi** [comment]
It works.

**Comment by markdimi** [comment]
I am running on the same issue. How did you make it to work?
