### ISSUE TITLE
Cannot import Watchdog

### ISSUE THREAD

**Issue by lukaxa888** [gorakhargosh/watchdog#875]
Hello, i tried to import watchdog after i sucesfully installed does not work
![image](https://user-images.githubusercontent.com/43339503/155122423-19047e8b-4570-4c65-af04-102ee1a5c33c.png)
![image](https://user-images.githubusercontent.com/43339503/155122475-08bc9136-d781-4da6-a07b-14bc45ab8a88.png)
Tried to uninstall and install again with no sucess.

**Comment by BoboTiG** [comment]
That's because your own script is also called "watchdog" (whatever the case). Rename it to something else, and it will work.
