### ISSUE TITLE
Event detection does not work when watching a folder that is bound as a volume to the Docker container

### ISSUE THREAD

**Issue by grigala** [gorakhargosh/watchdog#877]
Maybe anybody has faced the same issue before. 

I have a `FileSystemEventHandler` running under the Docker container, and the directory that is being watched is linked via volume bind. The issue is that the event handler only detects events within the tree state that is present during the start, but ignores newly created subfolder events, despite `recursive=True` being set. 

For example, if `FileSystemEventHandler` is watching `/` and I create a folder `/test/` or a file `/test.txt` inside it everything is fine, however  if I perform the same operations within the newly created child folder i.e. create `/test/test` folder or `/test/test.txt` file it is not doing anything. 

The code below behaves correct on my host machine, but suffers with the above described behavior under the Docker container when `DIR_TO_WATCH` is being bound as  a volume: 
```python
class CustomFileSystemEventHandler(FileSystemEventHandler):
   def on_created(self, event):
       if os.path.isdir(event.src_path):
           logging.info(f"A new directory has been {event.event_type}.")
       elif os.path.isfile(event.src_path):
           logging.info(f"File {event.src_path} has been {event.event_type}.")
           # Do Something
       else:
           logging.info(f"Ignoring event type {event.event_type}")

   def on_deleted(self, event):
      # Do Something


if __name__ == "__main__":
   LOGGING_FORMAT = '%(asctime)s - %(message)s'
   LOGGING_DATE_FORMAT = '%d-%b-%y %H:%M:%S'
   logging.basicConfig(format=LOGGING_FORMAT, datefmt=LOGGING_DATE_FORMAT, level=logging.INFO)

   event_handler = CustomFileSystemEventHandler()
   observer = Observer()
   observer.schedule(event_handler, DIR_TO_WATCH, recursive=True)
   observer.start()
   try:
       while True:
           time.sleep(1)
   finally:
       observer.stop()
       observer.join()

```

Any thoughts?

**Comment by grigala** [comment]
Switched to `PollingObserver` fixed it.

**Comment by RogueCultivators** [comment]
I solved it using PollingObserver
