### ISSUE TITLE
Watchmedo.tricks_from broken after latest upgrade

### ISSUE THREAD

**Issue by ginwakeup** [gorakhargosh/watchdog#879]
Hi,

we upgraded to latest version of the package and our tools are now crashing when invoking watchmedo.tricks_from method.

The exception:

```
  File "C:\Program Files\JetBrains\PyCharm 2021.3.2\plugins\python\helpers\pydev\pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2021.3.2\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "...", line 119, in <module>
    watchmedo.tricks_from(args)
TypeError: 'NoneType' object is not callable
```

The code:
```
args = parseArgs()
    if args.files:
        LOGGER.info("Starting Tricks Watcher...")

        # Launch watchmedo using input tricks configuration files.
        watchmedo.tricks_from(args)
```

**Comment by BoboTiG** [comment]
Could you share the tricks file to ease reproduction on my side?

**Comment by BoboTiG** [comment]
It is OK, I can reproduce easily. Working on a fix.

**Comment by BoboTiG** [comment]
Do you mind trying the version from the [BoboTiG:fix-879](https://github.com/BoboTiG/watchdog/tree/fix-879) branch to ensure my fix is working fine in your environment :pray: ? You could even hot-patch watchdogfor a quick test, here is the only change required:

```diff
diff --git a/src/watchdog/watchmedo.py b/src/watchdog/watchmedo.py
index 668984d..0841c9a 100755
--- a/src/watchdog/watchmedo.py
+++ b/src/watchdog/watchmedo.py
@@ -97,6 +97,7 @@ def command(args=[], parent=subparsers, cmd_aliases=[]):
         for arg in args:
             parser.add_argument(*arg[0], **arg[1])
             parser.set_defaults(func=func)
+        return func
     return decorator
 ```

**Comment by ginwakeup** [comment]
> Do you mind trying the version from the [BoboTiG:fix-879](https://github.com/BoboTiG/watchdog/tree/fix-879) branch to ensure my fix is working fine in your environment 🙏 ? You could even hot-patch watchdog for a quick test, here is the only change required:
> 
> ```diff
> diff --git a/src/watchdog/watchmedo.py b/src/watchdog/watchmedo.py
> index 668984d..0841c9a 100755
> --- a/src/watchdog/watchmedo.py
> +++ b/src/watchdog/watchmedo.py
> @@ -97,6 +97,7 @@ def command(args=[], parent=subparsers, cmd_aliases=[]):
>          for arg in args:
>              parser.add_argument(*arg[0], **arg[1])
>              parser.set_defaults(func=func)
> +        return func
>      return decorator
> ```

Yes this works, thanks @BoboTiG 
I will fix it locally for the moment, any ETA for the patch release?

**Comment by BoboTiG** [comment]
Great! Thanks for the test :muscle: 

ETA could be ASAP, I "just" need to fix tests. Working on it right now.

**Comment by BoboTiG** [comment]
Watchdog [2.1.7](https://github.com/gorakhargosh/watchdog/releases/tag/v2.1.7) is out :champagne:

**Comment by ginwakeup** [comment]
> Watchdog [2.1.7](https://github.com/gorakhargosh/watchdog/releases/tag/v2.1.7) is out 🍾

Thank you!
