### ISSUE TITLE
No notifications for permission changes on PollingObserver()

### ISSUE THREAD

**Issue by kchaksuvej** [gorakhargosh/watchdog#882]
I changed the permission of a file but no event was raised.
I am using PollingObserver() to monitor files on 2 machines with shared folder. It raised event changes such as modify or delete on file or directory.
But it does not raise modify event when I change file permission/owner.
Any suggestions. Thanks

**Comment by kurtmckee** [comment]
@gorakhargosh and @BoboTiG, this is a duplicate of #881. Please close this ticket.
