### ISSUE TITLE
no output from `watchmedo log`

### ISSUE THREAD

**Issue by xloem** [gorakhargosh/watchdog#913]
I'm not sure what `watchmedo log` is intended to do, but from the name I would expect output of events.

When I do:
`watchmedo log --patterns="*.py;*.txt"`

and then
`touch hi.txt`
in the same folder, I don't get any output.

Compare to `watchmedo shell-command --command='echo "${watch_src_path}"'` which shows the name of the file.

**Comment by brianthelion** [comment]
@xloem I encountered the same issue. `watchmedo log` is the obvious first thing to try when you're just starting to experiment with `watchdog`, the result is nonsensical, and this issue makes it appear that the package is low quality.

Anyway, after some poking around it looks like `watcmedo log --verbose` will show the `logging.info` dumps. IMHO this should be the default unless some other output is intended.

**Comment by xloem** [comment]
@BoboTiG what's the intended behavior here?

**Comment by brianthelion** [comment]
It looks like `watchmedo log` just delegates to `LoggerTrick` [here](https://github.com/gorakhargosh/watchdog/blob/21e9f4c6466b884f87ab39d704101fb4b8b9f3c6/src/watchdog/watchmedo.py#L413). The implementation of `LoggerTrick` is, in turn, a no-op:

https://github.com/gorakhargosh/watchdog/blob/21e9f4c6466b884f87ab39d704101fb4b8b9f3c6/src/watchdog/tricks/__init__.py#L82-L103

The `@echo_events` decorator is what actually calls `logger.info(...)`.

**Comment by xloem** [comment]
> `     """A simple trick that does only logs events."""`

I'm guessing that something like `--verbose` should be the default here.

**Comment by BoboTiG** [comment]
The `LoggerTrick` class seems outdated. I'll also check the code history, and see whzt was the original intended behavior.
