### ISSUE TITLE
The sdist is missing tox.ini

### ISSUE THREAD

**Issue by mtelka** [gorakhargosh/watchdog#928]
The sdist at PyPI is missing both `tox.ini` and `requirements-tests.txt` files.  Please add them to sdist to make the downstream testing easier.  Thanks.

**Comment by BoboTiG** [comment]
I would be glad to merge a PR :)

**Comment by mtelka** [comment]
Honestly, I do not know how this should be fixed because:

```
$ git clone https://github.com/gorakhargosh/watchdog.git
...
$ cd watchdog
$ git reset --hard v2.1.9
HEAD is now at 4cbf15c Release 2.1.9
$ python -m build --sdist --no-isolation
...
$ tar tvf dist/watchdog-2.1.9.tar.gz | egrep 'tox\.ini|requirements-tests\.txt' | wc -l
2
$
```

So maybe you should just upgrade your tools?  I tested the above with Python 3.9.15 and build 0.9.0.

**Comment by BoboTiG** [comment]
The packaging is automatically handle by that job: https://github.com/gorakhargosh/watchdog/blob/master/.github/workflows/build-and-publish.yml

Maybe should we list missing files into https://github.com/gorakhargosh/watchdog/blob/master/MANIFEST.in?

**Comment by mtelka** [comment]
Or replace `python setup.py sdist` [here](https://github.com/gorakhargosh/watchdog/blob/master/.github/workflows/build-and-publish.yml#L91) by something more modern?  I do not know what would fit better for you, but I think move out of `setup.py` is the way to go.

OTOH, `watchdog` is not converted to PEP 517 yet (`pyproject.toml` file is missing) so probably just [MANIFEST.in](https://github.com/gorakhargosh/watchdog/blob/master/MANIFEST.in) update is simpler.

Thanks.
