### ISSUE TITLE
error: legacy-install-failure (Watchdog)

### ISSUE THREAD

**Issue by bugsbunny110** [gorakhargosh/watchdog#932]
Hello,

When I am trying to install functions-framework, I got an error legacy-install-failure  related to watchdog. I read some articles about that but I do not understand how to fix that.

Thanks in advanced

MacBook:Google-Cloud-Function-alpaca karimayad$ pip install functions-framework
Collecting functions-framework
  Using cached functions_framework-3.2.1-py3-none-any.whl (30 kB)
Collecting flask<3.0,>=1.0
  Using cached Flask-2.2.2-py3-none-any.whl (101 kB)
Requirement already satisfied: click<9.0,>=7.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from functions-framework) (8.1.3)
Collecting watchdog>=1.0.0
  Using cached watchdog-2.1.9.tar.gz (119 kB)
  Preparing metadata (setup.py) ... done
Collecting cloudevents<2.0.0,>=1.2.0
  Using cached cloudevents-1.7.1-py3-none-any.whl (46 kB)
Collecting gunicorn<21.0,>=19.2.0
  Using cached gunicorn-20.1.0-py3-none-any.whl (79 kB)
Collecting deprecation<3.0,>=2.0
  Using cached deprecation-2.1.0-py2.py3-none-any.whl (11 kB)
Requirement already satisfied: Werkzeug>=2.2.2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from flask<3.0,>=1.0->functions-framework) (2.2.2)
Requirement already satisfied: Jinja2>=3.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from flask<3.0,>=1.0->functions-framework) (3.1.2)
Collecting itsdangerous>=2.0
  Using cached itsdangerous-2.1.2-py3-none-any.whl (15 kB)
Requirement already satisfied: setuptools>=3.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from gunicorn<21.0,>=19.2.0->functions-framework) (65.6.3)
Requirement already satisfied: packaging in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from deprecation<3.0,>=2.0->cloudevents<2.0.0,>=1.2.0->functions-framework) (21.3)
Requirement already satisfied: MarkupSafe>=2.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from Jinja2>=3.0->flask<3.0,>=1.0->functions-framework) (2.1.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from packaging->deprecation<3.0,>=2.0->cloudevents<2.0.0,>=1.2.0->functions-framework) (3.0.9)
Building wheels for collected packages: watchdog
  Building wheel for watchdog (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [53 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.9-universal2-cpython-311
      creating build/lib.macosx-10.9-universal2-cpython-311/watchdog
      copying src/watchdog/watchmedo.py -> build/lib.macosx-10.9-universal2-cpython-311/watchdog
      copying src/watchdog/version.py -> build/lib.macosx-10.9-universal2-cpython-311/watchdog
      copying src/watchdog/events.py -> build/lib.macosx-10.9-universal2-cpython-311/watchdog
      copying src/watchdog/__init__.py -> build/lib.macosx-10.9-universal2-cpython-311/watchdog
      creating build/lib.macosx-10.9-universal2-cpython-311/watchdog/utils
      copying src/watchdog/utils/patterns.py -> build/lib.macosx-10.9-universal2-cpython-311/watchdog/utils
      copying src/watchdog/utils/__init__.py -> build/lib.macosx-10.9-universal2-cpython-311/watchdog/utils
      copying src/watchdog/utils/dirsnapshot.py -> build/lib.macosx-10.9-universal2-cpython-311/watchdog/utils
      copying src/watchdog/utils/delayed_queue.py -> build/lib.macosx-10.9-universal2-cpython-311/watchdog/utils
      copying src/watchdog/utils/platform.py -> build/lib.macosx-10.9-universal2-cpython-311/watchdog/utils
      copying src/watchdog/utils/process_watcher.py -> build/lib.macosx-10.9-universal2-cpython-311/watchdog/utils
      copying src/watchdog/utils/bricks.py -> build/lib.macosx-10.9-universal2-cpython-311/watchdog/utils
      copying src/watchdog/utils/echo.py -> build/lib.macosx-10.9-universal2-cpython-311/watchdog/utils
      creating build/lib.macosx-10.9-universal2-cpython-311/watchdog/observers
      copying src/watchdog/observers/fsevents.py -> build/lib.macosx-10.9-universal2-cpython-311/watchdog/observers
      copying src/watchdog/observers/inotify.py -> build/lib.macosx-10.9-universal2-cpython-311/watchdog/observers
      copying src/watchdog/observers/__init__.py -> build/lib.macosx-10.9-universal2-cpython-311/watchdog/observers
      copying src/watchdog/observers/api.py -> build/lib.macosx-10.9-universal2-cpython-311/watchdog/observers
      copying src/watchdog/observers/inotify_buffer.py -> build/lib.macosx-10.9-universal2-cpython-311/watchdog/observers
      copying src/watchdog/observers/winapi.py -> build/lib.macosx-10.9-universal2-cpython-311/watchdog/observers
      copying src/watchdog/observers/read_directory_changes.py -> build/lib.macosx-10.9-universal2-cpython-311/watchdog/observers
      copying src/watchdog/observers/kqueue.py -> build/lib.macosx-10.9-universal2-cpython-311/watchdog/observers
      copying src/watchdog/observers/inotify_c.py -> build/lib.macosx-10.9-universal2-cpython-311/watchdog/observers
      copying src/watchdog/observers/polling.py -> build/lib.macosx-10.9-universal2-cpython-311/watchdog/observers
      copying src/watchdog/observers/fsevents2.py -> build/lib.macosx-10.9-universal2-cpython-311/watchdog/observers
      creating build/lib.macosx-10.9-universal2-cpython-311/watchdog/tricks
      copying src/watchdog/tricks/__init__.py -> build/lib.macosx-10.9-universal2-cpython-311/watchdog/tricks
      running egg_info
      writing src/watchdog.egg-info/PKG-INFO
      writing dependency_links to src/watchdog.egg-info/dependency_links.txt
      writing entry points to src/watchdog.egg-info/entry_points.txt
      writing requirements to src/watchdog.egg-info/requires.txt
      writing top-level names to src/watchdog.egg-info/top_level.txt
      reading manifest file 'src/watchdog.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '*.h' under directory 'src'
      adding license file 'LICENSE'
      adding license file 'COPYING'
      adding license file 'AUTHORS'
      writing manifest file 'src/watchdog.egg-info/SOURCES.txt'
      running build_ext
      building '_watchdog_fsevents' extension
      creating build/temp.macosx-10.9-universal2-cpython-311
      creating build/temp.macosx-10.9-universal2-cpython-311/src
      clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -DWATCHDOG_VERSION_STRING=\"2.1.9\" -DWATCHDOG_VERSION_MAJOR=2 -DWATCHDOG_VERSION_MINOR=1 -DWATCHDOG_VERSION_BUILD=9 -I/Library/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c src/watchdog_fsevents.c -o build/temp.macosx-10.9-universal2-cpython-311/src/watchdog_fsevents.o -std=c99 -pedantic -Wall -Wextra -fPIC -Wno-nullability-completeness -Wno-nullability-extension -Wno-newline-eof -Wno-error=unused-command-line-argument
      xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for watchdog
  Running setup.py clean for watchdog
Failed to build watchdog
Installing collected packages: watchdog, itsdangerous, gunicorn, flask, deprecation, cloudevents, functions-framework
  Running setup.py install for watchdog ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for watchdog did not run successfully.
  │ exit code: 1
  ╰─> [55 lines of output]
      running install
      /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.9-universal2-cpython-311
      creating build/lib.macosx-10.9-universal2-cpython-311/watchdog
      copying src/watchdog/watchmedo.py -> build/lib.macosx-10.9-universal2-cpython-311/watchdog
      copying src/watchdog/version.py -> build/lib.macosx-10.9-universal2-cpython-311/watchdog
      copying src/watchdog/events.py -> build/lib.macosx-10.9-universal2-cpython-311/watchdog
      copying src/watchdog/__init__.py -> build/lib.macosx-10.9-universal2-cpython-311/watchdog
      creating build/lib.macosx-10.9-universal2-cpython-311/watchdog/utils
      copying src/watchdog/utils/patterns.py -> build/lib.macosx-10.9-universal2-cpython-311/watchdog/utils
      copying src/watchdog/utils/__init__.py -> build/lib.macosx-10.9-universal2-cpython-311/watchdog/utils
      copying src/watchdog/utils/dirsnapshot.py -> build/lib.macosx-10.9-universal2-cpython-311/watchdog/utils
      copying src/watchdog/utils/delayed_queue.py -> build/lib.macosx-10.9-universal2-cpython-311/watchdog/utils
      copying src/watchdog/utils/platform.py -> build/lib.macosx-10.9-universal2-cpython-311/watchdog/utils
      copying src/watchdog/utils/process_watcher.py -> build/lib.macosx-10.9-universal2-cpython-311/watchdog/utils
      copying src/watchdog/utils/bricks.py -> build/lib.macosx-10.9-universal2-cpython-311/watchdog/utils
      copying src/watchdog/utils/echo.py -> build/lib.macosx-10.9-universal2-cpython-311/watchdog/utils
      creating build/lib.macosx-10.9-universal2-cpython-311/watchdog/observers
      copying src/watchdog/observers/fsevents.py -> build/lib.macosx-10.9-universal2-cpython-311/watchdog/observers
      copying src/watchdog/observers/inotify.py -> build/lib.macosx-10.9-universal2-cpython-311/watchdog/observers
      copying src/watchdog/observers/__init__.py -> build/lib.macosx-10.9-universal2-cpython-311/watchdog/observers
      copying src/watchdog/observers/api.py -> build/lib.macosx-10.9-universal2-cpython-311/watchdog/observers
      copying src/watchdog/observers/inotify_buffer.py -> build/lib.macosx-10.9-universal2-cpython-311/watchdog/observers
      copying src/watchdog/observers/winapi.py -> build/lib.macosx-10.9-universal2-cpython-311/watchdog/observers
      copying src/watchdog/observers/read_directory_changes.py -> build/lib.macosx-10.9-universal2-cpython-311/watchdog/observers
      copying src/watchdog/observers/kqueue.py -> build/lib.macosx-10.9-universal2-cpython-311/watchdog/observers
      copying src/watchdog/observers/inotify_c.py -> build/lib.macosx-10.9-universal2-cpython-311/watchdog/observers
      copying src/watchdog/observers/polling.py -> build/lib.macosx-10.9-universal2-cpython-311/watchdog/observers
      copying src/watchdog/observers/fsevents2.py -> build/lib.macosx-10.9-universal2-cpython-311/watchdog/observers
      creating build/lib.macosx-10.9-universal2-cpython-311/watchdog/tricks
      copying src/watchdog/tricks/__init__.py -> build/lib.macosx-10.9-universal2-cpython-311/watchdog/tricks
      running egg_info
      writing src/watchdog.egg-info/PKG-INFO
      writing dependency_links to src/watchdog.egg-info/dependency_links.txt
      writing entry points to src/watchdog.egg-info/entry_points.txt
      writing requirements to src/watchdog.egg-info/requires.txt
      writing top-level names to src/watchdog.egg-info/top_level.txt
      reading manifest file 'src/watchdog.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '*.h' under directory 'src'
      adding license file 'LICENSE'
      adding license file 'COPYING'
      adding license file 'AUTHORS'
      writing manifest file 'src/watchdog.egg-info/SOURCES.txt'
      running build_ext
      building '_watchdog_fsevents' extension
      creating build/temp.macosx-10.9-universal2-cpython-311
      creating build/temp.macosx-10.9-universal2-cpython-311/src
      clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -DWATCHDOG_VERSION_STRING=\"2.1.9\" -DWATCHDOG_VERSION_MAJOR=2 -DWATCHDOG_VERSION_MINOR=1 -DWATCHDOG_VERSION_BUILD=9 -I/Library/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c src/watchdog_fsevents.c -o build/temp.macosx-10.9-universal2-cpython-311/src/watchdog_fsevents.o -std=c99 -pedantic -Wall -Wextra -fPIC -Wno-nullability-completeness -Wno-nullability-extension -Wno-newline-eof -Wno-error=unused-command-line-argument
      xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> watchdog

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
MacBook:Google-Cloud-Function-alpaca karimayad$

**Comment by BoboTiG** [comment]
Hello,

We do not ship wheels for Python 3.11 yet. I'm on it!

**Comment by BoboTiG** [comment]
Wheels are online with the version [2.2.0](https://github.com/gorakhargosh/watchdog/releases/tag/v2.2.0).
