### ISSUE TITLE
BUG on latest version on Windows

### ISSUE THREAD

**Issue by gaetan1903** [gorakhargosh/watchdog#937]
```shell
$ watchmedo auto-restart --patterns="*.py;langs.json" --recursive -- python -c "import core;core.ampalibe.init.run()" 
failed to create process
```

with the old version it works, but with the last no

**Comment by BoboTiG** [comment]
Could be a duplicate of #935.

**Comment by gaetan1903** [comment]
when it's released ? or i install via master branch ?

**Comment by BoboTiG** [comment]
Right now, the release process is ongoing :)

**Comment by BoboTiG** [comment]
Can you confirm the [version 2.2.1](https://github.com/gorakhargosh/watchdog/releases/tag/v2.2.1) works for you, please?

**Comment by gaetan1903** [comment]
i confirm, it works fine with the latest version

Thank you
