### ISSUE TITLE
mypy typing error with watchdog.events.FileSystemEventHandler

### ISSUE THREAD

**Issue by bossebandowski** [gorakhargosh/watchdog#943]
Hello,

I am using watchdog in a project with strict typing enabled. The code is working fine, but mypy which we use for type checking keeps complaining about the following class definition.

```
from watchdog.events import FileSystemEventHandler

class SomeFileChanged(FileSystemEventHandler):
    """Class for observing if some file has changed."""

    def __init__(self, outer: SomeCustomType) -> None:
        """Init method for observer of changed files.

        Parameters:
        outer (SomeCustomType): outer class for callback
        """
        super().__init__()
        self.outer = outer
```

Here's the error:

```
myfile.py:12345: error: Class cannot subclass "FileSystemEventHandler" (has type "Any")  [misc]
```

Based on [this issue](https://github.com/python/mypy/issues/4180), it seems to me like the reason for this error is the watchdog `__init__.py` file which is currently empty.

Is there a reason why the file is empty and the customary `__all__ = ("FileSystemEventHandler", ...)` is missing?

**Setup**
```
Ubuntu20.04
python3.10
watchdog==2.2.1
mypy==0.991
```

**Comment by BoboTiG** [comment]
It is better with the version from the `master` branch? At least with the commit 17f6d0cca188bcbd43f1700046fbf33db51e945.

**Comment by BoboTiG** [comment]
I checked, and as of v4.0.2 it works like a charm.
