### ISSUE TITLE
reloads each time I open file in VScode

### ISSUE THREAD

**Issue by tasiotas** [gorakhargosh/watchdog#967]
Hi,

- Django 4.0.8
- Werkzeug==2.2.3
- watchdog==2.3.1
- WSL

Every time I open python file in VScode, Django reloads. Says change detected in bunch of files, but in reality I just opened one of them.

```
django  |  * Detected change in '/app/config/schema.py', reloading
django  |  * Detected change in '/app/config/urls.py', reloading
django  |  * Restarting with watchdog (inotify)
```
Works fine in 2.1.9
I saw similar [issue](https://github.com/gorakhargosh/watchdog/issues/949), seemed like same as mine, but I still have it in 2.3.1

Thanks

**Comment by n1ngu** [comment]
Werkzeug 2.3 was just released last week

**Comment by tasiotas** [comment]
yep, all good , thank you!
