### ISSUE TITLE
mypy error: Variable "watchdog.observers.Observer" is not valid as a type

### ISSUE THREAD

**Issue by JohnStrunk** [gorakhargosh/watchdog#982]
Since the release of 3.0.0, I'm getting errors from mypy when I use `Observer` as a type in my function definitions:

```python
from watchdog.observers import Observer

def myfn(obs: Observer) -> None:
    pass

myobs = Observer()
myfn(myobs)
```

```console
> mypy zz.py
zz.py:3: error: Variable "watchdog.observers.Observer" is not valid as a type  [valid-type]
zz.py:3: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
Found 1 error in 1 file (checked 1 source file)

> python --version
Python 3.11.0
```

Platform: Windows

**Comment by BoboTiG** [comment]
@altendky would it be possible to have a look 🙏🏻 ?

**Comment by altendky** [comment]
Maybe this is a relevant minimal example of the issue.

https://mypy-play.net/?mypy=1.1.1&python=3.11&gist=08674707b9b4b878a182dc85a145c91f
```python
from typing import Type, Union


class Base:
    ...

class M(Base):
    ...

class N(Base):
    ...

# a runtime condition that mypy should not resolve
runtime_condition: bool

C: Union[Type[M], Type[N]]
D: Type[Base]

if runtime_condition:
    C = M
    D = M
else:
    C = N
    D = N

ia: C
ib: D

if runtime_condition:
    E = M
else:
    E = N

ic: E
```
```
main.py:26: error: Variable "__main__.C" is not valid as a type  [valid-type]
main.py:26: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
main.py:27: error: Variable "__main__.D" is not valid as a type  [valid-type]
main.py:27: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
main.py:32: error: Cannot assign multiple types to name "E" without an explicit "Type[...]" annotation  [misc]
main.py:32: error: Incompatible types in assignment (expression has type "Type[N]", variable has type "Type[M]")  [assignment]
Found 4 errors in 1 file (checked 1 source file)
```

**Comment by BoboTiG** [comment]
The simplest solution, as @nhairs pointed, is to use `BaseObserver` for the type:

```diff
@@ -1,7 +1,7 @@
-from watchdog.observers import Observer
+from watchdog.observers import BaseObserver, Observer
 
-def myfn(obs: Observer) -> None:
+def myfn(obs: BaseObserver) -> None:
     pass
 
 myobs = Observer()
 myfn(myobs)
```

I would close the issue since this is a clean one. OK for you?

**Comment by JohnStrunk** [comment]
@BoboTiG, thanks for distilling that solution.

I'm fine w/ closing the issue. If I run into problems making the change, I'll re-open for further discussion.

**Comment by nhairs** [comment]
There's probably 2 things that we can do to help reduce the number of people that hit this issue.

The first would be to add documentation, probably to the Quick Start guide explaining that for typing purposes you should use `BaseObserver`.

The second would be to add proper type annotations [to `Observer`](https://github.com/gorakhargosh/watchdog/blob/6b74737501c85df9b9c2585faef4797a5250171b/src/watchdog/observers/__init__.py#L89) which I think would be as simple as `Observer: type[BaseObserver] = _get_observer_cls()`
